### ISSUE TITLE
Self-Signed SSL certificates not working

### ISSUE THREAD

**Issue by Adriaanse** [Unidata/netcdf-java#1003]
In netcdf-java release 5.5.2 and current source there is an bug in the relatively new code that handles self-signed SSL certificates.

The HTTPSession class contains a private class LooseTrustStrategy which implements TrustSelfSignedStrategy as follows:

    _@Override
    public boolean isTrusted(final X509Certificate[] chain, String authType) throws CertificateException {
      try {
        if (super.isTrusted(chain, authType))
          return true;
        // check expiration dates
        for (X509Certificate x5 : chain) {
          try {
            x5.checkValidity();
          } catch (CertificateExpiredException | CertificateNotYetValidException ce) {
            return true;
          }
        }
      } catch (CertificateException e) {
        return true; // temporary
      }
      return false;
    }_

Clearly both catch clauses should return false instead of true and the final return statement should return true instead of false ?

**Comment by JohnLCaron** [comment]
I would recommend to remove this capability altogether.

**Comment by haileyajohnson** [comment]
What is this use case for this? Our systems group was also in favor of removing this entirely.

**Comment by haileyajohnson** [comment]
Closed by #1004
