### ISSUE TITLE
NcMLWriter does not write integer variable values as integers

### ISSUE THREAD

**Issue by hlernbeiss** [Unidata/netcdf-java#103]
In NetCDF-Java version 5.0.0:

In method `makeValuesElement(Variable, boolean)` of class `NcMLWriter` there obviously is the intention to separate writing of floating point values and integer values (by the boolean variable `isRealType`), but appending to the string builder (buffer) is always made through `StringBuilder.append(double)` since the used ternary operator will always have a result of type `double`. A statement like `if (isRealType) buff.append(iter.getDoubleNext()); else buff.append(iter.getIntNext());` should be used instead.

**Comment by JohnLCaron** [comment]
Thanks, you're very right. Will fix in versions 5 and 6.
