### ISSUE TITLE
[5.5.3]: Fix GRIB IOSP to ensure time coordinates are monotonically increasing

### ISSUE THREAD

**Issue by ethanrd** [Unidata/netcdf-java#1060]
### Versions impacted by the bug

v5.x

### What went wrong?

For variables where the data values are valid on a time interval, e.g., total precipitation, the GRIB IOSP calculates time coordinates from the set of time intervals specified in the GRIB records. When the set of time intervals are irregular and overlapping, using the mid-point of each interval as the time coordinate values can result in a coordinate variable that is not monotonically increasing.

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

N/A

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by ethanrd** [comment]
This issue (and soon to be added PRs) replaces PR #1043 in order to separate the solution for datasets with 1-D time from the solution for FMRC datasets with 2-D time (model run and valid).

**Comment by ethanrd** [comment]
I have solution for datasets with 1-D time and will submit soon, probably early next week. Still working on solution for FMRC datasets with 2-D time.

**Comment by pedro-cf** [comment]
NetCDF example: https://drive.google.com/file/d/1ypnvsHarmJxZgeueGXXSDw4yVNaSi_mO/view?usp=sharing

**Comment by pedro-cf** [comment]
> NetCDF example: https://drive.google.com/file/d/1ypnvsHarmJxZgeueGXXSDw4yVNaSi_mO/view?usp=sharing

this same NetCDF can be accessed via this thredds server (wms): http://thredds.maretec.org/thredds/catalog/IST_MOHID_BIO_DATA/TAGUS_0.007DEG_50L_1H/FORECAST/catalog.html?dataset=MOHIDWATERDatasetScan/TAGUS_0.007DEG_50L_1H/FORECAST/2023051700.nc
