### ISSUE TITLE
Split visad module

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#107]
Related to Unidata/netcdf-java#105

Split the `visad` module into the following new modules:

* mcidas/gempak
* visad5

The dividing line here is that mcidas and gempak IOSPs depend very little on `visad.jar`, and can pull in the necessary code to keep them working. the vis5d IOSP depends heavily on `visad.jar`, so it can be split off into its own module to allow uses to pull in that dependency or not.

**Comment by JohnLCaron** [comment]
Vis5D is not currently loaded into the IOSPs. 
So the only possible use is someone calling it directly, maybe the IDV?
Would be easy to check by grepping their code.

**Comment by lesserwhirls** [comment]
I don't see Vis5DIosp used anywhere in the IDV. I'll ask our committees in a few weeks to see if they know of anyone using that capability, and I'll check the download metrics on visadCdm.jar from nexus to get an idea of overall usage.

**Comment by lesserwhirls** [comment]
Closed by Unidata/netcdf-java#123
