### ISSUE TITLE
Use Server Provider interface for protocols (S3, HDFS, dap4, other…)

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#109]
Currently dods, dap4 are done by reflection in `ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile`

**Comment by lesserwhirls** [comment]
HDFS, S3 being added in v5.3 (currently in a feature branch over at https://github.com/Unidata/thredds)

**Comment by JohnLCaron** [comment]
See #118
