### ISSUE TITLE
Upgrade to current gradle release

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#110]
Upgrade the project to use the latest version of gradle (currently using v3.5.1, latest is v5.6.2). This will allow us to at least attempt to build and test the project with Java 11 (although still only using Java 8 features).

**Comment by willglynn** [comment]
Latest is now v6.1.1, which appears to be remain suitable from a Java support perspective:

> Gradle 6.0 now supports Java 13.
> 
> Gradle supports running on JDK8 through JDK13. JDK6 and 7 can still be used for compilation and testing.

**Comment by lesserwhirls** [comment]
Forgot to close this out, but we're now on Gradle 6.5.1 (`maint-5.x`, `develop` branches)
