### ISSUE TITLE
Deprecate ucar.nc2.dt

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#113]
Deprecate classes in `ucar.nc2.dt`.

* `ucar.nc2.dt.grid` deprecated in favor of `ucar.ft2.coverage`
* `ucar.nc2.dt.radial` deprecated in favor of `ucar.ft.radial`

Actual removal of `ucar.nc2.dt` will not occur until netcdf-java v7.

**Comment by JohnLCaron** [comment]
Deprecated in version 5. Can close.
