### ISSUE TITLE
how to read CDL file in Java

### ISSUE THREAD

**Issue by zyxgis** [Unidata/netcdf-java#1149]
how to read CDL file and transform CDL file to nc file in Java with netcdf-java?

**Comment by haileyajohnson** [comment]
You'll probably want to use the [`ncgen` utility](https://docs.unidata.ucar.edu/nug/current/netcdf_utilities_guide.html#guide_ncgen) to create either the nc file itself of Java code that generated the nc file.

**Comment by zyxgis** [comment]
i want extract partial information of CDL to JSON , and then to create nc file with the result.
