### ISSUE TITLE
[5.5.4+]: CF 1.9 and Geostationary projection

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#1200]
### Versions impacted by the bug

v5.x

### What went wrong?

The latest CF Convention release (1.10) and apparently the prior release (1.9) now specify that the x and y coordinate variables must have standard_name attributes with values "projection_x_angular_coordinate" and "projection_y_angular_coordinate" rather than the previously specified values of "projection_x_coordinate" and "projection_y_coordinate". This thoroughly messes up using NJ's geostationary projected grid handling.

At first look, it seems that adding a couple more definitions to `ucar.nc2.constants.C`F, and then modifying the if statements in `ucar.nc2.dataset.conv.CF1Convention `and `ucar.nc2.internal.dataset.conv.CF1Convention` that discover the projection x and y axes is sufficient to fix this. At least doing so with my local copy of NJ was sufficient to enable working with the grid and to make a plot.

Before I submit a pull request, though, is there anything else I should keep in mind?

ETA: This was brought to my attention by someone at EUMETSAT, who said his particular group is trying to bring their data products up to compliance with CF 1.9 (or later).

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by haileyajohnson** [comment]
Nothing else I know of to consider, @ethanrd can you think of anything?

**Comment by ethanrd** [comment]
Only thing is (probably clear already but just to be complete and explicit) both `projection_[x|y]_angular_coordinate` and `projection_[x|y]_coordinate` need to be recognized as old data will still have the non-`angular_` version. And it probably should not depend on the CF version as it is only a deprecation.

**Comment by rschmunk** [comment]
@ethanrd, What I did was add the angular coordinate standard name as acceptable. No way was I taking out the old non-angular coordinate standard name.

You can take a look at the June 14 commit on [rschmunk/netcdf-java](https://github.com/rschmunk/netcdf-java) to see what little I found seemed necessary.

**Comment by ethanrd** [comment]
@rschmunk - Yeah, I figured you were on it. Looks good. Thanks!

**Comment by rschmunk** [comment]
Resolved by PR #1202.
