### ISSUE TITLE
DOC: Oudated link to ncml XSD in NCML documentation

### ISSUE THREAD

**Issue by abel-bzz** [Unidata/netcdf-java#1271]
### Versions impacted by the bug

Latest NCML documentation (June 27, 2022)

### What went wrong?

The XSD located at https://schemas.unidata.ucar.edu/netcdf/ncml-2.2.xsd that is linked in the documentation at https://docs.unidata.ucar.edu/thredds/ncml/2.2/index.html#advanced-ncml is not the same as the one in https://github.com/Unidata/netcdf-java/blob/maint-5.x/cdm/core/src/main/resources/resources/nj22/schemas/ncml-2.2.xsd even though the version number is the same (2.2).

In particular the unsigned types are missing in the xsd linked in the documentation which causes issues for tools that may base their implementation on this XSD (such as [xncml](https://github.com/xarray-contrib/xncml)).

Note
----
I'm not sure where the documentation for ncml is, sorry if this issue is on the wrong repository.

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

N/A

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by tdrwenski** [comment]
Thanks for bringing this bug to our attention! We have just updated the schema on https://schemas.unidata.ucar.edu/netcdf/ncml-2.2.xsd to match the one on GitHub, as the changes are backwards compatible. But we will try to ensure that this uses semantic versioning correctly in the future.
