### ISSUE TITLE
Deprecation warnings reccomend switching to non-public methods

### ISSUE THREAD

**Issue by ed-erwin-tf** [Unidata/netcdf-java#1386]
Compiling my code against cdm-core 5.6.0 gives some deprecation warnings.  The javadocs suggest switching to other methods, but in some cases those methods are not public and I cannot use them.

`makeValidPathName(java.lang.String)` in `ucar.nc2.NetcdfFile` has been deprecated
We are recommended to use `NetcdfFiles.makeValidPathName`, but **it is not public**.

`makeValidSectionSpecName(java.lang.String)` in `ucar.nc2.NetcdfFile` has been deprecated
We are recommended to use  use `NetcdfFiles.makeValidSectionSpecName`, but **it is not public**.

**Comment by tdrwenski** [comment]
Thanks for reporting this! I will make those methods in `NetcdfFiles` public.
