### ISSUE TITLE
Cannot open HDF-EOS swath file with unlimited dimension

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#149]
A user reported that Panoply could not open an HDF-EOS file and there was a "Conflicting Dimensions" exception message. The same occurs using toolsUI and IDV. Although the copy of Panoply was using netCDF-Java 5.1, I encountered the same problem when investigating using 5.3-SNAPSHOT.

The exception is thrown at line 262 of `ucar.nc2.iosp.hdf4.HdfEos`.After adding a lot of additional logging msgs, I eventually found that what was going on is that the particular swath file has metadata stating that the time dimension nTime has length 1, like so:

```
	GROUP=SWATH_1
		SwathName="MOP02"
		GROUP=Dimension
			OBJECT=Dimension_1
				DimensionName="Unlim"
				Size=-1
			END_OBJECT=Dimension_1
			OBJECT=Dimension_2
				DimensionName="nTime"
				Size=1
			END_OBJECT=Dimension_2

```

However, the time dimension actually has 221967 steps, and the various variables that use that dimension specify a MaxdimList of unlimited, e.g.,

```
			OBJECT=DataField_2
				DataFieldName="SolarZenithAngle"
				DataType=H5T_NATIVE_FLOAT
				DimList=("nTime")
				MaxdimList=("Unlim")
			END_OBJECT=DataField_2
```

So it seems that on trying to acquire the dataset, the netCDF-Java library is figuring out that there are 221967 timesteps in the example file, but when it circles around and does some testing to verify that this is an HDF-EOS file, it's running into that bit of metadata that says the nTime dimension has size 1. And thus the conflicting dimensions exception gets thrown.

I commented out that exception throw, and was then able to open the file and plot from the data within with problem. However, I don't know that that's  the best solution for this problem. 🙄

For an example dataset, I ran my tests using ftp://l5ftl01.larc.nasa.gov/pub/MOPITT/MOP02J.008/2017.08.17/MOP02J-20170807-L2V18.0.3.he5

**Comment by JohnLCaron** [comment]
I just ported HDF-EOS to new 5.3 framework. Would be happy to test if we can get an example file.

**Comment by rschmunk** [comment]
@JohnLCaron, see ftp URL given at the end of my initial post.

**Comment by JohnLCaron** [comment]
The webpage at ftp://l5ftl01.larc.nasa.gov/pub/MOPITT/MOP02J.008/2017.08.17/MOP02J-20170807-L2V18.0.3.he5 might be temporarily down or it may have moved permanently to a new web address.

sean, have you downloaded?

**Comment by lesserwhirls** [comment]
Hi @JohnLCaron - I did snag a copy, but not from the ftp server (I could not connect via browser or command line). I googled the file name and found it [here](https://l5eil01.larc.nasa.gov:22000/MOPITT/MOP02J.008/2017.08.07/MOP02J-20170807-L2V18.0.3.he5) (same server, but through https, ~320 MB).

**Comment by rschmunk** [comment]
Nice catch on that URL, @lesserwhirls. I was a little surprised to be given an ftp address in the first place as the agency has been shutting ftp sites down. I guess this one got the axe in the last week or two.

**Comment by JohnLCaron** [comment]
Sending a PR for this.
Would be good to put the file into TestDir.cdmUnitTestDir + "/formats/hdf5/MOP02J-20170807-L2V18.0.3.he5"

**Comment by JohnLCaron** [comment]
Like @rschmunk, I didnt actually fix anything, just removed the fatal error. Its pretty obvious the ODL is wrong. Could retrofit to earlier versions.

**Comment by JohnLCaron** [comment]
I guess this "works" now.
