### ISSUE TITLE
Creating Groups with NetcdfFileWriter.addGroup not working

### ISSUE THREAD

**Issue by omarbenhamid** [Unidata/netcdf-java#157]
I use netcdf-java 5.2.0 on Windows with JDK 1.8.0. The file is Netcdf 4 format (HDF style)

It fails when I try to create a netcdf group with : 
```java
NetcdfFileWriter n = NetcdfFileWriter.openExisting(filePath);
n.setRedefineMode(true);
Group rootGroup = n.addGroup(null, "");
n.addGroup(rootGroup, "test");
n.setRedefineMode(false);

```

I get : 
```
java.lang.NullPointerException
	at ucar.nc2.jni.netcdf.Nc4Iosp.updateDimensions(Nc4Iosp.java:445)
	at ucar.nc2.jni.netcdf.Nc4Iosp.updateDimensions(Nc4Iosp.java:496)
	at ucar.nc2.jni.netcdf.Nc4Iosp.flush(Nc4Iosp.java:3502)
	at ucar.nc2.NetcdfFileWriter.rewrite(NetcdfFileWriter.java:938)
	at ucar.nc2.NetcdfFileWriter.setRedefineMode(NetcdfFileWriter.java:928)
....
```

**Comment by omarbenhamid** [comment]
BTW. The issue is that groupHash does not contain a group id for the newly created group, so get() returns `null` `Integer` object  then java raises a NullPointerException when it tries to auto unbox it to an `int`. 

I managed to work around it by modifying the beginning of updateDimensions in Nc4Iosp.java this way, but I don't know if it is the right way / place to define the newly created groups ... :

```java
	Integer grpid = groupHash.get(g);

	if(grpid == null) { //GRoup does not exist ?
		IntByReference grpidp = new IntByReference();
	    int ret = nc4.nc_def_grp(groupHash.get(g.getParentGroup()), g.getShortName(), grpidp);

	    if (ret != 0)
	        throw new IOException(ret + ": " + nc4.nc_strerror(ret));
	    grpid = grpidp.getValue();
	    createGroup(new Group4(grpid, g, null));
	    //nc4.nc_enddef(grpid);
	    
	}
```

**Comment by lesserwhirls** [comment]
It's hard to tell from your error message text, but is this failing on the call to `n.setRedefineMode(false)`in your code?

In general, `NetcdfFileWriter.openExisting` can only be used to to read/write data to existing variables, and cannot create new objects (https://docs.unidata.ucar.edu/netcdf-java/5.2/javadoc/ucar/nc2/NetcdfFileWriter.html#openExisting-java.lang.String-). That said, we need to do a better job with our error handling for this case rather than throw an NPE.

What is the overall goal you are trying to achieve with your sample code?

**Comment by omarbenhamid** [comment]
The sample code was just a simple snippet to isolate what I tought was a big.

I have existing netcdf files to which I need to add new Variables in new groups.
If setRedifinitionMode(true) must not be called on a file obtained with openExisting() that would mean that there is no supported way to add groups to existing netcdf 4 files ?
I believe the issue is also raised with createNew. I'll try and tell you.

**Comment by JohnLCaron** [comment]
Moving forward, we will not support modifying existing netcdf files. Use the C library for that.

closed, will not fix.
