### ISSUE TITLE
RadialVariable has bad implementation for getUnitsString()

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf-java#160]
I'm not sure how important it is, but if you look at `getUnitsString` for a `RadialVariable`, the implementation is:

https://github.com/Unidata/netcdf-java/blob/8f15ecf5a8937dc3ec6b7de87a8fd02636ba0bfc/cdm/core/src/main/java/ucar/nc2/dt/radial/AbstractRadialAdapter.java#L375-L377

That's...less than helpful. I know at least NEXRAD puts useful information in the `units` attribute. Any reason not to forward onto that here?

**Comment by lesserwhirls** [comment]
At least it works with UDUNITS? No reason ignore what's provided by an IOSP at a lower level, unless the unit is "OMGWHY"...that one is not even recognized by UDUNITS and should just be ignored I think.

![OMGWHY](https://media.giphy.com/media/MsUKQTpWE3UxW/giphy.gif)
