### ISSUE TITLE
Bug controlling when hdf5/netdf4 uses jna vs java iosp.

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#175]
I didnt intend to change this, find out what happened:

From #126: "This started showing up when the way we load IOSPs changed with PR 101 (see https://github.com/Unidata/netcdf-java/pull/101/files for the changes)."

**Comment by lesserwhirls** [comment]
OK, I think I found it. Specifically it was this:

https://github.com/Unidata/netcdf-java/pull/101/files#diff-012e4ec8c93cb12e0fbe471801cf22d3R842-R843

Uncommenting those two lines causes the `H5Iosp` to take precedence, no matter what. What the Dap4 test code was doing, and still does in `DapTestCommon`, is try to force the `Nc4Iosp` to the top of the registered IOSP list to make sure the C library is used for reading (via the `NetcdfFile.registerIOProviderPreferred(NC4IOSP, ucar.nc2.iosp.hdf5.H5iosp.class);` call) (which is now deprecated), and up until this point in the `NetcdfFile` code, the `Nc4Isop` is selected, but then at this point, it's forced over to `H5iosp`. Forcing reading through the c library is less than ideal, but having two code paths in production code based on the availability of the C library is...well, what we have now. Dap4 production code makes direct jna calls if the C library is available, regardless of IOSPs.

Interesting note here...the DapTestCommon class never calls `iospDeRegister()` (also deprecated) to undo this loading choice, so after this point, the Nc4Iosp will still appear at the top of the `registeredProviders` list. That has bit us before on the server side, back with the Dap4 production code changed the IOSP order (as still done in the tests) and, once a dap4 end point was called, the server would die with a segfault produced somewhere in the HDF C code.

I would much rather we only use the netCDF-C library for local debugging / initial development purposes (if necessary), and never use it explicitly for reading in our code, especially in a viral way mucking with the IOSP order, and most certainly in production code. A hidden, ticking time bomb is never fun when it's found.

**Comment by JohnLCaron** [comment]
Good catch. Im submitting PR180

Id like to get the functionality back for DapTestCommon to use Nc4Iosp for the duration of its testing.
