### ISSUE TITLE
Exception opening remote GRIB datasets

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#181]
@lesserwhirls, I'm trying to determine if an issue related loading remote GRIB files was ever addressed. Specifically I'm looking at Unidata/thredds#797

I had a user write in today about trying to load remote GRIB-2 files and I found it was reporting the severe "reading/Creating gbx9 index for file" exception in Grib2CollectionBuilder.

I had a dim recollection that I'd encountered trouble in the past with loading remote GRIB-2 files, and der Google led me right to Unidata/thredds#797

Although my prior issue was using NJ 4.6, I used the latest 5.3 SNAPSHOT today. @cofinoa commented previously that the problem did not occur with NJ 4.2 but that things got broken in 4.3.

Confusingly, there were also some GRIB-2 files in the same remote directory that Grib2Iosp wouldn't claim, and so they were instead reported as "not a valid CDM file".

**Comment by JohnLCaron** [comment]
The problem with GRIB is that we have to write an index file. I think one can control where that index file is kept, but the details probably depend on the calling environment and whether its a single file or a collection. If this is still an issue, I will try to track it down.

**Comment by rschmunk** [comment]
@JohnLCaron, I'm still getting the "not a valid CDM file" response when trying to load a remote GRIB file using a recent 5.4.2-SNAPSHOT.

**Comment by JohnLCaron** [comment]
See Issue #638
