### ISSUE TITLE
DatasetUrl.findDatasetUrl(location) fails with https://upwell.pfeg.noaa.gov/erddap/griddap/jplAquariusSSS3MonthV5

### ISSUE THREAD

**Issue by noaaroland** [Unidata/netcdf-java#185]
Version 5.2.0 with openjdk version "1.8.0_212" on Ubuntu 16.4

When opening the above OPeNDAP URL with 5.2 the findDatasetUrl fails with a 404 not found.

When opening the same URL with 4.6.14 the code goes straight to the:
 NetcdfDataset ncd = NetcdfDataset.acquireDataset(location, task);

and the data set opens just fine.

**Comment by rschmunk** [comment]
The dataset can be loaded using NJ 5.1, but fails with a 5.3 snapshot.

**Comment by lesserwhirls** [comment]
Fixed by Unidata/netcdf-java#188 - thank you for the report @noaaroland and additional info @rschmunk !
