### ISSUE TITLE
Problem with results of the ucar.nc2.Variable.read() method.

### ISSUE THREAD

**Issue by V-F** [Unidata/netcdf-java#186]
There is a problem after [changes](https://github.com/Unidata/netcdf-java/commit/7b31c20eeb67fc3c4a14c17694277bfd16f0b61f) in the method [DataBTree.Node::first](https://github.com/Unidata/netcdf-java/commit/7b31c20eeb67fc3c4a14c17694277bfd16f0b61f#diff-7330567f14c5cc91e1f2cd0a29431448R233). The method ucar.nc2.Variable.read() returns result array that contains invalid values in the first elements of first dimesion of the for example 5AMP-History__0/Bx variable for the specified file.
[HistDumpTest9.zip](https://github.com/Unidata/netcdf-java/files/4064149/HistDumpTest9.zip)

**Comment by JohnLCaron** [comment]
I believe this is the problem that #194 fixes. However, this file has uncovered a related problem that I will investigate.

**Comment by JohnLCaron** [comment]
Ok, I have a fix for this. Will add to #194.

**Comment by JohnLCaron** [comment]
Thanks for the bug report and data file. What is it?

**Comment by V-F** [comment]
> Ok, I have a fix for this. 
I have tested. Thank you for fixing this bug.

> Thanks for the bug report and data file. What is it?
I'm not sure I can assume that this file was generated by some generator such as [this](https://data.giss.nasa.gov/gistemp/maps/index_v4.html). It is used as one of the files for automatic testing.
