### ISSUE TITLE
How to add relative path of TableB and TableD in custom Bufr lookup file?

### ISSUE THREAD

**Issue by Yaqiang** [Unidata/netcdf-java#217]
I can register a custom bufr lookup file using the function: ucar.nc2.iosp.bufr.tables.BufrTables.addLookupFile( String filename)  and given the whole paths of TableB and TableD.

`CMA.23, 38,   0,        23,    -1,   -1, D:/MyProgram/Distribution/Java/MeteoInfo/MeteoInfo/tables/bufr/cma_bufr_tableb.csv, wmo_csv, D:/MyProgram/Distribution/Java/MeteoInfo/MeteoInfo/tables/bufr/cma_bufr_tabled.csv, wmo_csv`

The question is how to use relative paths of TableB and TableD in lookup file? For example the lookup file and TableB/TableD files are in same folder. The following line in the lookup file didn't work.

`CMA.23, 38,   0,        23,    -1,   -1, ./cma_bufr_tableb.csv, wmo_csv, ./cma_bufr_tabled.csv, wmo_csv`

**Comment by lesserwhirls** [comment]
Greetings @Yaqiang! When the code reads in the lookuptable, it tries a few ways to read in the tables listed in lookup file:

https://github.com/Unidata/netcdf-java/blob/3bfb098f94a96d1b94497159f6382bba08917da9/bufr/src/main/java/ucar/nc2/iosp/bufr/tables/BufrTables.java#L1359-L1377

The `FileInputStream` call needs the full path (at least as we have it coded now). One thing you could do, and what we do with our tables, it reference them from the resource path. For example, 

https://github.com/Unidata/netcdf-java/blob/3bfb098f94a96d1b94497159f6382bba08917da9/bufr/src/main/resources/resources/bufrTables/local/tablelookup.csv#L33

ultimately maps to the tables inside the bufr jar (`bufr.jar/resources/bufrTables/wmo`)

**Comment by Yaqiang** [comment]
Thanks @lesserwhirls for your response! Yes, it's possible to solve the problem through uzip jar file, update resources files and re-pack jar file. Or it's considerable to support relative path in BufrTables.java file. I recently solve the problem through adding an additional lookup fullpath file and update the fullpath according the relative path lookup file. Following is Jython function to load a lookup file with relative path.

```python
def add_bufr_lookup(lookup):
    """
    Add bufr lookup file for reading bufr files with local code tables.

    :param lookup: (*str*) The bufr lookup file path.
    """
    lookup_fp = lookup + '.fullpath'
    is_fullpath = True if os.path.isfile(lookup_fp) else False
    if is_fullpath:
        with open(lookup_fp, 'r') as f:
            for line in f:
                line = line.lstrip()
                if line.startswith('#'):
                    continue
                paras = line.split(',')
                tb_fn = paras[6].strip()
                td_fn = paras[8].strip()
                if (not os.path.isfile(tb_fn)) or (not os.path.isfile(td_fn)):
                    is_fullpath = False
                    break

    if not is_fullpath:
        apath = os.path.dirname(lookup)
        os.chdir(apath)
        data = ''
        with open(lookup, 'r') as f:
            for line in f:
                line = line.lstrip()
                if line.startswith('#'):
                    data += line
                    continue
                paras = line.split(',')
                tb_fn = paras[6].strip()
                td_fn = paras[8].strip()
                tb_fn = os.path.abspath(tb_fn)
                td_fn = os.path.abspath(td_fn)
                line = line.replace(paras[6], tb_fn)
                line = line.replace(paras[8], td_fn)
                data += line
        with open(lookup_fp, 'w') as f:
            f.write(data)

    BufrTables.addLookupFile(lookup_fp)
```

**Comment by lesserwhirls** [comment]
You should not need to unjar, add, and rejar `bufr.jar`, but rather package your tables in a separate jar, and include that jar on the classpath. I will look at adding the ability to read tables relative to the lookup file location.

**Comment by Yaqiang** [comment]
@lesserwhirls Thanks for your kindly help!

**Comment by JohnLCaron** [comment]
@lesserwhirls can we close this?
