### ISSUE TITLE
Issues with failing Jenkins tests

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#224]
There are 4 failing tests here:

https://jenkins-aws.unidata.ucar.edu/job/netcdf-java/85/testReport/junit/ucar.nc2.dataset/

1. I removed these two files, they didnt make sense i think, but send me a copy and ill recheck:

cdmUnitTest/conventions/cedric/test.ncml 
cdmUnitTest/conventions/default/HistDumpTest9.nc     

2. these are not failing locally for me. maybe i modified them?

cdmUnitTest/conventions/wrf/wrfout_01_000000_0003.ncml
cdmUnitTest/conventions/wrf/wrf_masscore.ncml

Im sending my versions so you can see if they are different (github wont accept them here so im emailing)

(sorry if thats the problem, I should be syncing any changes I make)

**Comment by lesserwhirls** [comment]
* `cdmUnitTest/conventions/wrf/wrf_masscore.ncml`:
   ~~~
   Current Test data <   <variable name='Times' type='string' shape='Time DateStrLen' />
   ---
   New file >            <variable name='Times' type='char' shape='Time DateStrLen' />
   ~~~
* `cdmUnitTest/conventions/wrf/wrfout_01_000000_0003.ncml`
   ~~~
   Current Test data <   <variable name='Times' type='string' shape='Time DateStrLen' />
   ---
   New file >            <variable name='Times' type='char' shape='Time DateStrLen' />
   ~~~
* `cdmUnitTest/conventions/default/HistDumpTest9.nc` was added based on this [comment](https://github.com/Unidata/netcdf-java/pull/197#issuecomment-582024823), and was submitted as part of [this issue](https://github.com/Unidata/netcdf-java/issues/186). I can move it from `cdmUnitTest/conventions/default/` to `cdmUnitTest/formats/netcdf4/` and write a test that specifically tests the reported problem.
* `cdmUnitTest/conventions/cedric/test.ncml`:   ¯\\_(ツ)_/¯ I want to look at this one a bit more to understand what's happening. Here is a copy of it the NcML: [test.zip](https://github.com/Unidata/netcdf-java/files/4298426/test.zip)

**Comment by JohnLCaron** [comment]
none of these are failing
