### ISSUE TITLE
Dimension builder failing on unlimited dimension

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#226]
In `NcStream.java`, we get a failure when decoding a dimension that is unlimited:

https://github.com/Unidata/netcdf-java/blob/4405f1eb4ca50d6258fbc99899845f17af78e4a5/cdm/core/src/main/java/ucar/nc2/stream/NcStream.java#L415-L420

The dimension builder call should be something like:

```
Dimension.builder()
    .setName(name)
    .setIsUnlimited(dim.getIsUnlimited())
    .setIsShared(!dim.getIsPrivate())
    .setIsVariableLength(dim.getIsVlen())
    .setLength(dimLen)
    .build();
```

Need to check all uses of the `Dimension.Builder builder(String name, int length)` constructor to make sure we're not setting a trap for unlimited dimensions.

Bigger question is what to do to make that specific constructor more safe. Maybe we should just defer all validation until `build()`?

**Comment by JohnLCaron** [comment]
@lesserwhirls can we close this?
