### ISSUE TITLE
ncstream and structure with vlen member

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#230]
We are running into an NPE when dealing with ncstream and structure data in which one of the members is a vlen. The following code will trigger the issue:

~~~java
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Formatter;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import ucar.ma2.InvalidRangeException;
import ucar.nc2.NetcdfFile;
import ucar.nc2.NetcdfFiles;
import ucar.nc2.util.CompareNetcdf2;
import ucar.unidata.util.test.TestDir;
import ucar.unidata.util.test.category.NeedsCdmUnitTest;

@Category(NeedsCdmUnitTest.class)
public class TestStreamStructVlen {

  String filename = TestDir.cdmUnitTestDir + "formats/netcdf4/vlen/IntTimSciSamp.nc";

  @Test
  public void testVlenStreamVsLocal() throws IOException, InvalidRangeException {
    File tempFile = File.createTempFile("tmp-", "-ncstream");
    tempFile.deleteOnExit();
    try (NetcdfFile ncf = NetcdfFiles.open(filename)) {
      NcStreamWriter writer = new NcStreamWriter(ncf, null);
      try (OutputStream fos = new BufferedOutputStream(new FileOutputStream(tempFile), 50 * 1000)) {
        writer.streamAll(fos);
      }
      NetcdfFile ncfStream = NetcdfFiles.open(tempFile.getCanonicalPath());
      CompareNetcdf2.compareFiles(ncf, ncfStream, new Formatter(System.out), true, false, false);
    }
  }
}
~~~

In this code, we open a netCDF-4 file from [thredds-test-data](https://github.com/unidata/thredds-test-data) ([ncstream_vlen.zip](https://github.com/Unidata/netcdf-java/files/4332126/ncstream_vlen.zip)), write out as ncstream to a temp file, read the temp file back in, and try to compare against the original netCDF-4 file. NPE is coming from `ucar.ma2.ArrayStructureBB.getArray(int recnum, StructureMembers.Member m)`:

https://github.com/Unidata/netcdf-java/blob/fae08ee5347d12690ab8bced7db80b9d9317ba26/cdm/core/src/main/java/ucar/ma2/ArrayStructureBB.java#L179-L187

specifically `return (Array) heap.get(heapIndex)`, as `heap` is `null` at the time `getArray` is called. Based on what I've seen elsewhere, my current working though is `NcStreamIosp` needs some additions for Structures, probably here:

https://github.com/Unidata/netcdf-java/blob/fae08ee5347d12690ab8bced7db80b9d9317ba26/cdm/core/src/main/java/ucar/nc2/stream/NcStreamIosp.java#L156-L164

like making a making sure vlen data gets added to the structure array heap (just a guess based on comments in `H5IospNew`, such as `// strings and vlens are stored on the heap, and must be read separately`). Although, the method following `readStructureData` (`readVlenData`) has the comment `// lOOK probably doesnt work`, which makes me a little nervous.

**Comment by JohnLCaron** [comment]
will not fix.
ncstream is deprecated in favor of cdmr.
