### ISSUE TITLE
Changes to cdmUnitTest files

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#242]
1. remove conventions/default/* 
Existing file is not the right example for default, and it fails.

2. remove formats/grib2/gfs_4_20130830_1800_144.grb2
Last record is truncated, data reading fails.

**Comment by JohnLCaron** [comment]
Another one:

in ~cdmUnitTest/conventions/wrf/wrf_masscore.ncml

  <variable name='Times' type='string' shape='Time DateStrLen' />

should be 

  <variable name='Times' type='char' shape='Time DateStrLen' />

**Comment by JohnLCaron** [comment]
````
  <variable name='Times' type='string' shape='Time DateStrLen' />
````
should be
````
  <variable name='Times' type='char' shape='Time DateStrLen' />

````

**Comment by lesserwhirls** [comment]
Updated in https://github.com/unidata/thredds-test-data rsync repository and will be picked up by Jenkins. Thanks @JohnLCaron!

**Comment by JohnLCaron** [comment]
java.io.IOException: java.io.IOException: Cant read file:/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/hdf4/MOD021KM.A2004328.1735.004.2004329164007.hdf.hexdat.txt: not a valid CDM file.

**Comment by lesserwhirls** [comment]
Thank you @JohnLCaron - I just removed that one from the test data.
