### ISSUE TITLE
Dataset class throws a NPE when Access element exists but service does not.

### ISSUE THREAD

**Issue by noaaroland** [Unidata/netcdf-java#270]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue

v5.2.0

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

Java 11.0.5

* a description of the issue with the steps needed to reproduce it

Traverse through the catalog and check hasAccess on each data set. One such data set has an Access object with a null service.  Line 118 of the Dataset class gets the service and asks for the type without checking if the service is null. See attached code. Catalog is:
https://www.ncei.noaa.gov/thredds/marine-ocean/ersst.xml

[Traverse.txt](https://github.com/Unidata/netcdf-java/files/4536354/Traverse.txt)

**Comment by lesserwhirls** [comment]
Greetings @noaaroland! Thank you for the detailed report! I see in the catalog that there is an element:

```
<access urlPath="ersstv3Agg" serviceName="ersstAgg"/>
```

I do not see a service named `ersstAgg` in any `<service>` element though, which is the source of the null in this case. Not sure if that is a valid access element (would be interesting to see the NcML backing this aggregation, as I am guessing there it's a typo).

If I do a check for null first, it looks like things work our correctly in the end. I'll have a PR up and the fix will be part of the next release (either today or tomorrow).

**Comment by noaaroland** [comment]
Thanks @lesserwhirls 

I think it is indeed the "right" behavior to prevent the crash when a client is trying to read a catalog configured in this way.

We can speculate that perhaps the person setting up the catalog made a mistake. What THREDDS does to warn or prevent that mistake at configuration time is still an open question. A warning when  the such a configuration catalog is read is probably about right. I didn't test what happens when THREDDS starts with configuration catalog like this.
