### ISSUE TITLE
netcdf-java fails to authenticate against AWS load balanced services.

### ISSUE THREAD

**Issue by ndp-opendap** [Unidata/netcdf-java#283]
Greetings,

I am working with DAP servers that require authenticated access and that are living behind a load balancer, in particular the AWS ALB. I have had trouble getting Panoply to work in this environment, so knowing that it and IDV both utilize netcdf-java for their DAP functionality I tried IDV.

I tried using IDV(5.7 downloaded today) to make the same access (NASA VPN only):

- https://opendap.sit.earthdata.nasa.gov/hyrax/data/nc/coads_climatology.nc

And it failed in a manner similar to Panoply, but it did write a bunch of log output into the parent shell. Of particular interest, 46 pairs of warnings:

```
WARNING: Invalid cookie header: "Set-Cookie: AWSALB=XgUtDYlzJFV+QV18sCdJ28FsyUDBObxfo0QwZSlZ4pHC513iB9U5daQCJSxrbeOu709tWYUco70kq1FHk8tuyXH0P3qJc6rYejum03dt6Dxss0qITZ1eBI3FwdBg; Expires=Wed, 13 May 2020 18:38:15 GMT; Path=/". Invalid 'expires' attribute: Wed, 13 May 2020 18:38:15 GMT

WARNING: Invalid cookie header: "Set-Cookie: AWSALBCORS=XgUtDYlzJFV+QV18sCdJ28FsyUDBObxfo0QwZSlZ4pHC513iB9U5daQCJSxrbeOu709tWYUco70kq1FHk8tuyXH0P3qJc6rYejum03dt6Dxss0qITZ1eBI3FwdBg; Expires=Wed, 13 May 2020 18:38:15 GMT; Path=/; SameSite=None". Invalid 'expires' attribute: Wed, 13 May 2020 18:38:15 GMT
```
And a few others along the lines of:
```
WARNING: Invalid cookie header: "Set-Cookie: sit_urs_user_already_logged=yes; domain=earthdata.nasa.gov; path=/; expires=Thu, 07 May 2020 18:38:58 GMT". Invalid 'expires' attribute: Thu, 07 May 2020 18:38:58 GMT

WARNING: Invalid cookie header: "Set-Cookie: _urs_sit-gui_session=41e8834d75ffff6f6b18d10ed3d73e8c; path=/; expires=Thu, 07 May 2020 18:38:58 GMT; HttpOnly". Invalid 'expires' attribute: Thu, 07 May 2020 18:38:58 GMT
```
I'll attached the entire output here: [idv-ngap-alb-errors.log](https://github.com/Unidata/netcdf-java/files/4589088/idv-ngap-alb-errors.log)

The problem cookies are important:
- **sit_urs_user_already_logged** Authentication (Utilized by Earthdata Login)
- **_urs_sit-gui_session** Authentication (Utilized by Earthdata Login)
- **AWSALB** The AWSALB cookie is used by the ALB to create sticky sessions so authenticated access works through the load balancer, basically ensuring the a particular session is tied to a particular DAP server instance. If this warning indicates that it's not being ingested by netcdf-java, then the authentication is unlikely to succeed. 
- **AWSALBCORS** This cookie is part of a Cross Origin Resource Sharing scheme used in AWS.

And the warnings are all stemming from the `expires` attribute:
> Invalid 'expires' attribute: Thu, 07 May 2020 18:39:03 GMT

And I also found this: https://github.com/elastic/support-diagnostics/issues/233 which might suggest that org.apache.http.client may need some tuning in the netcdf-java library, probably in the venerable DConnect2.java class.

Has anyone else run into this problem with the netcdf-java libraries or the clients based upon them?

Sincerely,

Nathan

**Comment by rschmunk** [comment]
@ndp-opendap, Is that URL accessible to anyone with an Earthdata account and who is on the NASA VPN? I have tried to access it, both using Panoply and a web browser, and failed. With Panoply, I am seeing a "IOException: Unauthorized to open dataset".

**Comment by ndp-opendap** [comment]
> @ndp-opendap, Is that URL accessible to anyone with an Earthdata account and who is on the NASA VPN? I have tried to access it, both using Panoply and a web browser, and failed. With Panoply, I am seeing a "IOException: Unauthorized to open dataset".

That URL https://opendap.sit.earthdata.nasa.gov/hyrax/data/nc/coads_climatology.nc is on a NASA VPN that is associated with the NGAP effort. I use a Code400 RSA key and the PulseSecure VPN client to connect to Earthdata Gateway 32 (edgate32) located here: https://edgate32.eno.ecs.nasa.gov

I'm afraid that if you can't get in there, then you can't hit that URL. 

So. Many. Rules.

N

**Comment by ndp-opendap** [comment]
Also: you have to be set up to authenticate with Earthdata Login. Here's how I would test it:  I put my EDL credentials in my `~/.netrc` file. Both the UAT and SIT environments have their own EDL instances so you have to have credentials for one or both of:
- `sit.urs.earthdata.nasa.gov`
- `uat.urs.earthdata.nasa.gov`
My `.netrc` file looks a bit like this:
```
machine uat.urs.earthdata.nasa.gov
    login ndp
    password somespecialthing

machine sit.urs.earthdata.nasa.gov
        login ndp
        password someotherspecialthing
```
With the EDL credentials sorted out and my system on the `edgate32` VPN I am able to use command line cURL to access the granule metadata like this:
```
curl -n -c ~/ursCookies -b ~/ursCookies -L https://opendap.sit.earthdata.nasa.gov/hyrax/data/nc/coads_climatology.nc.dds
```

**Comment by rschmunk** [comment]
Hmm, I can log into the site at urs.earthdata.nasa.gov, but not e.g. sit.urs.earthdata.nasa.gov. But it probably doesn't matter anyway. When I try to access the coads_climatology.nc  dataset using Panoply, the invalid cookie warnings start showing up in log messages even before I try to authenticate.

I'll take another look at this Friday and see if the discussion in the elastic/support-diagnostics issues is any help.

**Comment by ndp-opendap** [comment]
Hi Robert,

> Hmm, I can log into the site at urs.earthdata.nasa.gov, but not e.g. sit.urs.earthdata.nasa.gov.

The user lists for urs.earthdata.nasa.gov,  sit.urs.earthdata.nasa.gov, and disjoint uat.urs.earthdata.nasa.gov are essentially disjoint. You have to register as a "new" user in each environment.


> But it probably doesn't matter anyway. When I try to access the coads_climatology.nc dataset using Panoply, the invalid cookie warnings start showing up in log messages even before I try to authenticate.

Well at least it consistent and repeatable!

Sean @ Unidata reached out to me and I think we're going to utilize ToolsUI for debugging if it will reproduce the failure - all these apps are using netcdf-java and I think, under the hood, all of this is routed through a class called DConnect2.java that James Gallagher and I wrote in the Pliocene...


> On May 7, 2020, at 9:18 PM, R. Schmunk <notifications@github.com> wrote:
> 
> 
> Hmm, I can log into the site at urs.earthdata.nasa.gov, but not e.g. sit.urs.earthdata.nasa.gov. But it probably doesn't matter anyway. When I try to access the coads_climatology.nc dataset using Panoply, the invalid cookie warnings start showing up in log messages even before I try to authenticate.
> 
> I'll take another look at this Friday and see if the discussion in the elastic/support-diagnostics issues is any help.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

= = =
Nathan Potter                        ndp at opendap.org
OPeNDAP, Inc.                        +1.541.231.3317

**Comment by lesserwhirls** [comment]
Yes, the requests go through  `DConnect2`, but `DConnect2` was modified at some point to use our thin-ish layer on top of Apache httpclient (`httpservices`). One thing we could do pretty quickly is modify the client builders in `ucar.httpservices.HTTPMethod`, `ucar.httpservices.HTTPSession` to use set the CookieSpec, as suggested in elastic/support-diagnostics#233. Since I have zero hope of being able to test this first-hand (as @ndp-opendap said, So. Many. Rules.), I'm happy to provide jars with a quick fix to see if that solves the issue. Trying toolsUI is but one way.

**Comment by ndp-opendap** [comment]
Hi Sean,

I tried ToolsUI in a series of NASA deployments, and I had the same problems, with mostly expected differences in all of them. (tl;dr - skip to bottom)

Control URL (no authentication): 
    http://test.opendap.org/opendap/data/nc/coads_climatology.nc

**VPN access only (SIT)**
- DAP Server: opendap.uat.earthdata.nasa.gov
- EDL SSO: sit.urs.earthdata.nasa.gov
- Test URL: https://opendap.sit.earthdata.nasa.gov/hyrax/data/nc/coads_climatology.nc

**Localhost plus authentication via UAT (VPN access)**
- DAP Server: localhost:8080
- EDL SSO: uat.urs.earthdata.nasa.gov
- Test URL: https://localhost:8080/hyrax/data/nc/coads_climatology.nc

**Localhost plus authentication via Production URS**
- DAP Server: localhost:8080
- EDL SSO: urs.earthdata.nasa.gov
- Test URL: https://localhost:8080/hyrax/data/nc/coads_climatology.nc

**NASA production on premises DAP service**
- DAP Server: https://goldsmr4.gesdisc.eosdis.nasa.gov
- EDL SSO: urs.earthdata.nasa.gov
- Test URL: https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2_MONTHLY/M2TMNXAER.5.12.4/2008/MERRA2_300.tavgM_2d_aer_Nx.200807.nc4

The _Invalid cookie header_ warnings for the AWS cookies `AWSALB` & `AWSALBCORS` only show up in the first scenario, which is the only scenario in which there is an AWS load balancer in play.
```
[07:26:29.980 WARN  o.a.h.c.p.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: AWSALB=cK5IBT6HmtKRAjFbrSxKxDqNxlql4SeWSM1C2JpSwj2dnWXcZ4vtkYYPpO3USmtaeNyi4j3oFfI2AXveSDedO1Z1xNM4IEhUWKdZr9qSFLbf4IqaG1BRHL3IACfV; Expires=Fri, 15 May 2020 14:26:29 GMT; Path=/". Invalid 'expires' attribute: Fri, 15 May 2020 14:26:29 GMT
[07:26:29.981 WARN  o.a.h.c.p.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: AWSALBCORS=cK5IBT6HmtKRAjFbrSxKxDqNxlql4SeWSM1C2JpSwj2dnWXcZ4vtkYYPpO3USmtaeNyi4j3oFfI2AXveSDedO1Z1xNM4IEhUWKdZr9qSFLbf4IqaG1BRHL3IACfV; Expires=Fri, 15 May 2020 14:26:29 GMT; Path=/; SameSite=None". Invalid 'expires' attribute: Fri, 15 May 2020 14:26:29 GMT
```
All the scenarios with the exception of the last exhibited the _Invalid cookie header_ warnings for the URS cookies `sit_urs_user_already_logged` & `_urs_sit-gui_session` cookies: 
```
[07:26:48.890 WARN  o.a.h.c.p.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: sit_urs_user_already_logged=yes; domain=earthdata.nasa.gov; path=/; expires=Sat, 09 May 2020 14:26:48 GMT". Invalid 'expires' attribute: Sat, 09 May 2020 14:26:48 GMT
[07:26:48.891 WARN  o.a.h.c.p.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: _urs_sit-gui_session=b1d0c91840a8426405f45760804f1cba; path=/; expires=Sat, 09 May 2020 14:26:48 GMT; HttpOnly". Invalid 'expires' attribute: Sat, 09 May 2020 14:26:48 GMT
```
Thinking that I had found a way to let you replicate the error I went into NASA GESDISC and found this DAP dataset:

http://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2_MONTHLY/M2TMNXAER.5.12.4/2008/MERRA2_300.tavgM_2d_aer_Nx.200807.nc4

Which, in theory, would exhibit the same cookie issues. Unfortunately it faiedl further upstream, apparently  upset about the SSL certs:
```
ucar.httpservices.HTTPException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at ucar.httpservices.HTTPMethod.executeRaw(HTTPMethod.java:378)
	at ucar.httpservices.HTTPMethod.execute(HTTPMethod.java:320)
	at ucar.nc2.dataset.DatasetUrl.checkIfDods(DatasetUrl.java:426)
	at ucar.nc2.dataset.DatasetUrl.disambiguateHttp(DatasetUrl.java:375)
	at ucar.nc2.dataset.DatasetUrl.findDatasetUrl(DatasetUrl.java:153)
	at ucar.nc2.ui.ToolsUI.openFile(ToolsUI.java:1202)
```
Which my browser (and probably yours too) will accept without complaint. 

Maybe this is another separate but related issue?

**Summary**
- We can test with ToolsUI easily.
- We don't have to test against the VPN protected services to see the cookie problems.
- It seems like the AWS cookies are having the same issue as the EDL cookies so a fix is likely to work for both cases.
- If the SSL certs thing was sorted you might be able to replicate at least the EDL cookies part of the problem.

**Comment by lesserwhirls** [comment]
The issue with SSL is related to the version of Java you are using (it is likely missing one or more trusted certs). I'm able to hit that url using toolsUI without the `SSLHandshakeException` running under  `adoptopenjdk-8u242-b08`. I see the "Invalid cookie header" warnings after I authenticate with my EDL credentials. While that does not impact my ability to actually read the data in this case, it does give me something to work with.

**Comment by lesserwhirls** [comment]
Ok, setting the `CookieSpec` on the `RequestConfig` makes the warning disappear, so that gives me hope it will work for the AWS ALB as well.

**Comment by rschmunk** [comment]
Applying @lesserwhirls's changes to a local copy of 5.4 SNAPSHOT, and using my urs.earthdata login, I was able to open the file at http://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2_MONTHLY/M2TMNXAER.5.12.4/2008/MERRA2_300.tavgM_2d_aer_Nx.200807.nc4 in Panoply with Java 9.

First time failed with an exception about a broken pipe. Likely that was just a symptom of a failed authentication, as it worked on the second try with no alterations to my code.

**Comment by lesserwhirls** [comment]
Thank you for testing this @rschmunk! I merged in the change and published new snapshots (here is [toolsUI](https://artifacts.unidata.ucar.edu/repository/unidata-all/edu/ucar/toolsUI/5.4.0-SNAPSHOT/toolsUI-5.4.0-20200513.141840-35.jar)).

**Comment by ndp-opendap** [comment]
Thanks @lesserwhirls and @rschmunk ! 

I just downloaded the snapshot you linked above and it was able to access a dataset on the NASA UAT Hyrax instance, which is running inside a load balancer and that started this adventure:  http://opendap.uat.earthdata.nasa.gov/hyrax/data/nc/coads_climatology.nc
So this looks like this fix will work there too.

Thanks again!

**Comment by rschmunk** [comment]
@lesserwhirls, @ndp-opendap also reports that a Panoply built this afternoon using a 5.4 SNAPSHOT that includes #283 successfully loaded a dataset on the UAT server.
