### ISSUE TITLE
Cannot resolve edu.ucar:grib:5.3.2

### ISSUE THREAD

**Issue by blair-anson** [Unidata/netcdf-java#292]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
5.3.2

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
Ubuntu18
Java1.8
Maven3.3.9

* a description of the issue with the steps needed to reproduce it
I am upgrading from v5.2.0 to v.5.3.2 and I see the following error from maven
`Cannot resolve edu.ucar:grib:5.3.2`

I checked my pom.xml and I do have settings as per the link below. Also v5.2.0 worked fine

https://docs.unidata.ucar.edu/netcdf-java/5.3/userguide/using_netcdf_java_artifacts.html

**Comment by lesserwhirls** [comment]
I was able to remove my local .m2/repository cache, create the following new maven pom:

~~~xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.ucar</groupId>
  <artifactId>grib-artifact-test</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>grib-artifact-test</name>
  <url>http://maven.apache.org</url>
  <repositories>
    <repository>
      <id>unidata-all</id>
      <name>Unidata All</name>
      <url>https://artifacts.unidata.ucar.edu/repository/unidata-all/</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>edu.ucar</groupId>
      <artifactId>cdm-core</artifactId>
      <version>5.3.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>edu.ucar</groupId>
      <artifactId>grib</artifactId>
      <version>5.3.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
~~~

and successfully obtain the 5.3.2 release `grib` artifact when I run `mvn package`. I'm running maven 3.6.1 with OpenJDK 1.8.0_212-8u-03 on Windows.

What does the full output from maven look like?

**Comment by blair-anson** [comment]
@lesserwhirls Thanks, I cleared the mvn cache and it works fine now
