### ISSUE TITLE
cdm_data_type confusion

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/netcdf-java#299]
I don't think this is actually a problem with the NetCDF Java code, but wanted to get some clarification before I ask others to update the ACDD and NODC netCDF feature template documentation.

There seems to be some incorrect info on those pages on the cdm_data_type global attribute. As I understand it this attribute is specifically for NetCDF Java, and is used as an explicit way to designate the intended [FeatureType](https://github.com/Unidata/thredds/blob/target-4.3.22/cdm/src/main/java/ucar/nc2/constants/FeatureType.java).

Specifically, the problem applies to timeSeriesProfile (although I haven't experimented with the trajectory types). [According to the CF class](https://github.com/Unidata/thredds/blob/target-4.3.22/cdm/src/main/java/ucar/nc2/constants/CF.java#L157), the appropriate cdm_data_type (FeatureType) for timeSeriesProfile is STATION_PROFILE. However, the ACDD and NODC documents and example data sets don't seem to be aware of this cdm_data_type, suggesting STATION instead.

This causes problems with NetCDF Java. FeatureTypes/PointFeature seems to work fine with timeSeriesProfile data sets using cdm_data_type STATION, but FeatureTypes/FeatureScan reports an error:

```
Table TopScalars/PsuedoStructure(time)/MultidimPseudo(time,z) featureType STATION_PROFILE doesnt match desired type STATION
**Failed to find FeatureDatasetFactory for= /media/store/dl/problem.nc datatype=STATION
```

Language from the [NODC template page](http://www.nodc.noaa.gov/data/formats/netcdf/v1.1/):

> These data types do not map equally to the CF feature types. If the CF feature type = Trajectory Time Series, use "Trajectory"; if Point, Profile, or Time Series Profile, use "Station".

The [example NODC timeSeriesProfile cdl](http://data.nodc.noaa.gov/testdata/netCDFTemplateExamples/timeSeriesProfile/usgs_internal_wave_timeSeries.cdl) uses cdm_data_type STATION and produces above error.

The [ACDD wiki page](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_%28ACDD%29) lists an incorrect set of possible values for cdm_data_type:

> Current values: vector, grid, textTable, tin, stereoModel, video.

It also links to [the THREDDS InvCatalogSpec page)http://www.unidata.ucar.edu/software/thredds/current/tds/catalog/InvCatalogSpec.html#dataType, which lists an incomplete set of possible data type values and doesn't include STATION_PROFILE.

I'm guessing this is just a documentation problem. If so, it seems like three changes need to happen:
- Contact NODC to update their example data sets and suggested mapping documentation with the correct cdm_data_type mappings.
- Contact ACDD to update their wiki with the correct list of possible values.
- Update the THREDDS InvCatalogSpec page to list all possible values for dataType.

Does that sound right? Based on [CF.FeatureType](https://github.com/Unidata/thredds/blob/target-4.3.22/cdm/src/main/java/ucar/nc2/constants/CF.java#L157), these seem to be the correct mappings:

| CF | NetCDF Java |
| --- | --- |
| point | POINT |
| profile | PROFILE |
| timeSeries | STATION |
| timeSeriesProfile | STATION_PROFILE |
| trajectory | TRAJECTORY |
| trajectoryProfile | SECTION |

For context, I found these problems after following NODC template guidelines in the netCDF encoder I wrote for the [IOOS 52n SOS](https://github.com/ioos/i52n-sos) project. I now switched my code to [get the cdm_data_type directly from CF.FeatureType.convert[(https://github.com/ioos/i52n-sos/blob/master/coding-ioos-netcdf/src/main/java/org/n52/sos/encode/AbstractIoosNetcdfEncoder.java#L241), but want to get the documentation in wild corrected.

**Comment by niva83** [comment]
@lesserwhirls many thanks!
I would be happy to contribute with examples of nc files from wind energy community once we have some definitions `cdm_data_type.

**Comment by JohnLCaron** [comment]
I think this issue is complete. Feel free to reopen if needed.
