### ISSUE TITLE
NetCdfDataset.openDataset doesn't work for local OpeNDAP/DODS Files

### ISSUE THREAD

**Issue by furlong-tw** [Unidata/netcdf-java#346]
When working with a set of OpeNDAP/DODS files (.dods, .dds, .das) stored locally the general NetCdfDataset.openDataset method is not capable of of parsing the data.

### Steps to reproduce

- Using version 5.3.3
- Setup a data folder '/home/user/data' that contains wna20200629_00z.dods, wna20200629_00z.das, wna20200629_00z.dds files
- Call NetCdfDataset.openDataset with the path to the OpeNDAP/DODS files.

### Current behavior

Two possible options exist

1. Pass the base path to the files, example: "file:/home/user/data/wna20200629_00z". Results in "No such file or directory"
2. Pass the path to the primary data file, example:  "file:/home/user/data/wna20200629_00z.dods". Results in "File not readable wna20200629_00z.dods.dds".

### Expected Behavior

Calling:
 `NetCdfDataset.openDataset("file:/home/user/data/wna20200629_00z")` 
should produce the same result as:
` new DODSNetcdfFile( "file:/home/user/data/wna20200629_00z" )`

Directly instantiating a DODSNetCdfFile behaves as anticipated and ingests the local data file.

### Potential line of inquiry
The issue may be related to how arbitrary strings are correlated to DatasetUrl. If "file" protocol is passed then a file ending of ".dods", ".dds", or "das" is required to result in ServiceType.OPENDAP. If "dods" protocol is used then it is automatically modified to "https avoiding local file usage.

See [DatasetUrl](https://github.com/Unidata/netcdf-java/blob/7c2e46606fb2d2032c2612a900e7f6376c40bf42/cdm/core/src/main/java/ucar/nc2/dataset/DatasetUrl.java#L285):

```
  private static ServiceType decodePathExtension(String path) {
    // Look at the path extensions
    if (path.endsWith(".dds") || path.endsWith(".das") || path.endsWith(".dods"))
      return ServiceType.OPENDAP;

    if (path.endsWith(".dmr") || path.endsWith(".dap") || path.endsWith(".dsr"))
      return ServiceType.DAP4;

    if (path.endsWith(".xml") || path.endsWith(".ncml"))
      return ServiceType.NCML;
    return null;
  }
```

See [DODSNetcdfFile](https://github.com/Unidata/netcdf-java/blob/7c2e46606fb2d2032c2612a900e7f6376c40bf42/opendap/src/main/java/ucar/nc2/dods/DODSNetcdfFile.java#L176)

```
    String urlName = datasetURL; // actual URL uses http:
    this.location = datasetURL; // canonical name uses "dods:"
    if (datasetURL.startsWith("dods:")) {
      urlName = "http:" + datasetURL.substring(5);
    } else if (datasetURL.startsWith("http:")) {
      this.location = "dods:" + datasetURL.substring(5);
    } else if (datasetURL.startsWith("https:")) {
      this.location = "dods:" + datasetURL.substring(6);
    } else if (datasetURL.startsWith("file:")) {
      this.location = datasetURL;
    } else {
      throw new java.net.MalformedURLException(datasetURL + " must start with dods: or http: or file:");
    }
```

**Comment by lesserwhirls** [comment]
Thank you for your report @furlong-tw! This is fixed in the latest 5.4.0 SNAPSHOT. You will only need the `.dods` and `.das` files - more details can be found at https://docs.unidata.ucar.edu/netcdf-java/5.4/userguide/dataset_urls.html#opendap-datasets.
