### ISSUE TITLE
Data Type changes from ushort to uint in netcdf 4 to 5 migration

### ISSUE THREAD

**Issue by ghansham** [Unidata/netcdf-java#397]
Dear Sir 

I had a file with data type ushort. 
When I open it with netcdf-4.6.10. It shows data type as ushort (which is correct).
But when I open it with netcdf-5.0.0beta6 it show uint.

Should I try with netcdf-5 latest version.

**Comment by lesserwhirls** [comment]
It's quite possible there was a bug in beta6. Would you happen to have an example file?

**Comment by ghansham** [comment]
The bug continues in 5.3.3. And digging deep, bug is in GridDataset grids
and backing variables not the variables returned NetCDFFile class.

**Comment by ghansham** [comment]
Try writing a netcdf file with ushot variable with netcdf java 4 and read
it using ncj5.

Regards
Ghansham

**Comment by ghansham** [comment]
https://github.com/Unidata/netcdf-java/blob/592e87bb314351e11f53dc09aad13c801c9d7944/cdm/core/src/main/java/ucar/nc2/dataset/VariableDS.java#L238

I think this is where ushort is getting converted to uint. I am not sure though. Will check. But this has implication on file writing as well. Does that mean, if we read a ushort variable and then write it using CFWriter2 class, it will write it as uint. That will double up the size of file.

**Comment by lesserwhirls** [comment]
Greetings @ghansham - by default, `NetcdfDataset` and `GridDataset` will apply a set of [enhancements](https://docs.unidata.ucar.edu/netcdf-java/5.3/javadoc/ucar/nc2/dataset/NetcdfDataset.Enhance.html) to a `NetcdfFile` object, and the set of default enhancements in version 5 includes converting unsigned types. If you would like to turn that off, you can pass in the set enhancements you would like applied to the underlying `NetcdfFile` object. When reading through `GridDataset`, you need to at least include the [CoordSystems](https://docs.unidata.ucar.edu/netcdf-java/5.3/javadoc/ucar/nc2/dataset/NetcdfDataset.Enhance.html#CoordSystems) enhancement. The code would look something like this:

~~~java
Set<Enhance> enhancements = Collections.unmodifiableSet(EnumSet.of(Enhance.CoordSystems));
try (GridDataset gds = GridDataset.open(location, enhancements)) {
      GeoGrid grid = gds.findGridByName("unsigned_short");
      System.out.println(grid.getDataType());
}
~~~

which would print out `ushort`.

If you use the `GridDataset` from above in `CFGridWriter2`, the file that gets created will have the ushort variable.

**Comment by ghansham** [comment]
Thanks.. what is the downside of doing this?Why it is not the default case?
And does the scale offset, if applicable, for any variable, will work or
not?

regards
Ghansham

**Comment by JohnLCaron** [comment]
Enhancement is the default, with some work you can open a GridDataset without it. But why would you?

The scale/offset should work, let us know otherwise.

**Comment by ghansham** [comment]
Actually I am using ncwms2 (that uses ncj 5.0), original data is unsigned
short  (10 bit) data.
Actually there are a few more variables in the file that are computed using
the metadata in the original file.
Now while writing a netcdf file using ncj5, the file size blows up because
unsigned short (2bytes) data get upgraded to integer (4bytes) data.
Temporary work around for me was to change the data type from ushort to
short (because it is only 10 bits).

regards
Ghansham

**Comment by JohnLCaron** [comment]
So if you open the file with `ConvertUnsigned` turned off, does that solve the problem? Or you are saying ncwms opens it and you dont have a way of changing that?

Where does the conversion from ushort to integer happen?

Where do you "change the data type from ushort to short"?

**Comment by ghansham** [comment]
My data is written in hdf5. Then I create a netcdf file from that hdf5
adding a few data variables while computing them from metadata. In this
process, the ushort variables in the original hdf5 get upgraded to int
while writing them to nc file.

I change the data type from ushort to short while writing nc so that it
doesn't expand to int. I can share you the code whatever I am using.
I can modify ncwms code if I know there is a provision to avoid it.
What is theconverunsigned option? I will explore that.

Regards
Ghansham

**Comment by JohnLCaron** [comment]
You read in an hdf5 file and write out an netcdf3 file. netcdf3 doesnt have an unsigned type, so it gets converted to signed. The only way to safely do that is to promote ushort to int, causing a 2x expansion.

You change the data type from ushort to short to prevent the conversion. Which seems to me to be the best thing to do to not get the expansion. Now you have to document that the numbers in the file are really unsigned. How do you do that?

Where does ncwms come in?

**Comment by ghansham** [comment]
I can try writing netcdf4 if it supports unsigned. My area of concern is
that the data can fit in 2 bytes why to expand it in 4 bytes. Its wastage
of space in the name of performance when we know the application can
convert the  only the read ushort array to integer on the move which used
to be the case in earlier ncj versions. I remember there is a class
ucar.unidata.data.DataUtil class in idv repo

https://github.com/Unidata/IDV/blob/0e831178c80ab0e17dd6c8374895c932bcf241ff/src/ucar/unidata/data/DataUtil.java#L93

See this method. It does all the unsigned to signed conversion.

Ncwms2 comes into picture because I am using it for wms services for indian
satellite data.

Regards
Ghansham

**Comment by ghansham** [comment]
Data range is 10 bit (range: 0-1023) only so keeping data unsigned in java
atleast is an overkill.

**Comment by JohnLCaron** [comment]
We are doing workarounds for the fact that netcdf3 doesnt have unsigned
types. Use netcdf4 if you can.

**Comment by ghansham** [comment]
I will surely try and see if it works for me.
One more query do I gain in terms of I/O performance when I switch from nc3
to nc4.
Can we write nc4 without compression?
The reason behind these queries is while doing WMS I expect reading from
disk to be the main activity.
So decompressing every time will be expensive. Although ncwms provides
feature based caching on server side, still decompression has its own cost
attached.

**Comment by JohnLCaron** [comment]
It depends. You would have to measure it on real datasets. Sometimes compression is faster because it reduces IO. 

The general rule is: get it working  (correctly), measure bottlenecks, try to fix, measure if it helps.

**Comment by ghansham** [comment]
Thanks a lot for those guiding words. I have not yet tried nc4 data format
for unsigned data types.

Regards
Ghansham
