### ISSUE TITLE
ucar.unit.prefs and the TDS

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#41]
The removal of `ucar.unit.prefs` removed from `cdm` impacted the TDS (Unidata/tds#23) (oops). I need to setup a Jenkins run (hopefully tomorrow) to check PRs against netCDF-Java to make sure the TDS still at least compiles (not a show stopper for a PR, but at least we'd have a heads-up), but for now, this issue exists. Maybe the TDS does not need to be storing preferences this way, so one option is to stop the TDS from doing that. If it's needed, then we can do one of a few things:

1. Copy the same code into the TDS codebase (barf)
1. Have TDS depend on `uibase` (feels dirty)
1. Create a new utility focused module (meh...)
1. Move `ucar.unit.prefs` from `uibase` to an existing module
   * maybe `clcommon`, although that does not feel great because `clcommon` &rarr; "Client-side common library" (but TDS depends on that already and it's not client-side, so maybe it's not so bad?)

**Comment by JohnLCaron** [comment]
I think its really a tds problem, so ive commented on (Unidata/tds#23).
