### ISSUE TITLE
Preload remote data results in HTTP 414 error response

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#413]
Working with a recent NJ 5.4 snapshot.

A user testing a data catalog server reported that using Panoply, he was getting an HTTP 414 error response. In checking into this, I also encounter the issue with toolsUI. I am unable to test using IDV as that app is not notarized to work on up-to-date Macs, but I assume the same would happen there.

The test dataset is presently [located here](http://balto.opendap.org/opendap/nsidc/ATL08_20181016124656_02730110_002_01.h5).

The exception that occurs is in `DODSNetcdfFile`, where an attempt to preload data creates a URL that is exceptionally long. Exceptionally long, as in 13kB, and so the GET request is rejected.

A pertinent logging excerpt from Panoply follows, omitting the full GET query string:

```
000976 SEVERE: DODSNetcdfFile preloadData - ERROR readDataDDSfromServer on ?[13617 chars omitted]
000977 WARNING: NcDataset acquireNjDataset - IOException acquiring http://balto.opendap.org/opendap/nsidc/ATL08_20181016124656_02730110_002_01.h5, enhance true
java.io.IOException: Method failed:HTTP/1.1 414 Request-URI Too Long on URL= http://balto.opendap.org/opendap/nsidc/ATL08_20181016124656_02730110_002_01.h5.dods?[13617 chars omitted]
	at ucar.nc2.dods.DODSNetcdfFile.preloadData(DODSNetcdfFile.java:1538)
	at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:328)
	at ucar.nc2.dods.DODSNetcdfFileProvider.open(DODSNetcdfFileProvider.java:24)
	at ucar.nc2.dataset.NetcdfDatasets.openProtocolOrFile(NetcdfDatasets.java:431)
	at ucar.nc2.dataset.NetcdfDatasets.openDataset(NetcdfDatasets.java:152)
	at ucar.nc2.dataset.NetcdfDatasets.acquireDataset(NetcdfDatasets.java:280)
	at ucar.nc2.dataset.NetcdfDatasets.acquireDataset(NetcdfDatasets.java:257)
	...
```

So is this something where `DODSNetcdfFile` should be smart enough to reduce the size of the query strings it is issuing? Or should it even be requesting that much when the remote file is first accessed? Or a problem on the catalog server config? Or... any suggestions?

**Comment by lesserwhirls** [comment]
Greetings @rschmunk! It looks like `DODSNetcdfFile` tries to "preload scalars, coordinate variables, strings, small arrays", which looks to be most of the variables in that particular dataset. `DODSNetcdfFile` tries to fetch them in one request, but as you've found, that's not going to work. I *think* the fix is pretty simple...maybe. In the meantime, I believe you can call `DODSNetcdfFile.setPreload(false)` prior to making the request to turn off the preloading behavior as a temporary fix.

**Comment by rschmunk** [comment]
@lesserwhirls, Yes, calling `DODSNetcdfFile.setPreload(false)` does seem to work, for the time being. Now to decide whether that's the wisest thing.
