### ISSUE TITLE
CoordSysBuilder failing on GRIB collections

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#453]
When building coordinate systems for GRIB collections, `CoordSysBuilder` ends up creating coordinate systems with dimensions of the same short name but from different parent groups. This ends up causing the only two failures we see on Jenkins on the 5.4.x branch, specifically on test `ucar.nc2.dt.grid.TestGridSubsetCoordinateSystem.testCoordinateSystemDomain` for file `/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test data/cdmUnitTest/gribCollections/gfs_2p5deg/gfs_2p5deg.ncx4`.  In this test, when looking at variable `Best/Soil_temperature_depth_below_surface_layer`, we end up with a coordinate system of `TwoD/depth_below_surface_layer Best/depth_below_surface_layer` (so dimensions with the same short name, but from different parent groups - `TwoD` and `Best`).

**Comment by JohnLCaron** [comment]
Can this be closed?
