### ISSUE TITLE
Editing a NetCDF4 file without producing string-typed attributes

### ISSUE THREAD

**Issue by jhamberg** [Unidata/netcdf-java#472]
After opening a NetCDF4 file, redefining its variables and writing new data, most textual attributes appear to have been converted to a `string` format, even though they are not being touched in code:

Before editing:
```
// global attributes:
		:title = "MY_NETCDF" ;
		:Conventions = "CF-1.3" ;
		:grid_projection = "lonlat" ;
```

After editing: 
```
// global attributes:
		string :title = "MY_NETCDF" ;
		string :Conventions = "CF-1.3" ;
		string :grid_projection = "lonlat" ;
```

* Version of the library: edu.ucar:netcdf4:5.3.3
* System information: 
  * openjdk version "11.0.8" 2020-07-14
  * Linux 5.4.0-47-generic ~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  * Gradle 6.1.1
* Library classes used for writing:
  * NetcdfFileWriter
  * NetcdfFile
  * Array
  * Variable
  * Attribute

This is a problem, because tools like [ncview](http://meteora.ucsd.edu/~pierce/ncview_home_page.html) can no longer properly parse the data:
```
ncview: netcdf_title: internal error in the format of the netCDF input file; title
not in character format!  Setting title to NULL.
``` 
**Is there a way to omit this behavior?** Would switching to `Version.netcdf4_classic` work? If so, how would I accomplish this without creating a new file and copying all fields manually?

**Comment by lesserwhirls** [comment]
Greetings @jhamberg! Yes, setting the version to `Version.netcdf4_classic` would prevent that behavior. For existing files, you could use something similar to what is done by the command line utility `Nccopy`:

https://github.com/Unidata/netcdf-java/blob/5fd9cadfa8f5f1b607b39db3a41b40ce83d2a41e/cdm/core/src/main/java/ucar/nc2/write/Nccopy.java#L138-L146

This will still create a new file, but you won't have to manually include any attribute, variable, dimension, etc. You can also run the utility from the command line following [these instructions](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/cdm_utility_programs.html#nccopy).

A third option is to use the netCDF-C based `nccopy` [command line utility](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_utilities_guide.html#guide_nccopy) - I believe that will also turn `string` attributes into `char` attributes when the file is copied to a netCDF-4 classic model based file.

**Comment by jhamberg** [comment]
Thank you! I could not get `nccopy` to work with my file but the Java-based approach worked.
