### ISSUE TITLE
H5header warnings interfere with System.out logging

### ISSUE THREAD

**Issue by SethChampagneNRL** [Unidata/netcdf-java#600]
H5header warnings set to true cause all logging to System.out to break. Calling `H5header.setWarnings(false);` allows for logging to work again. 

It seems this line is the cause. It is hijacking System.out

https://github.com/Unidata/netcdf-java/blob/2292da0d2ad5118e62d9a9d52838759c5c189142/cdm/core/src/main/java/ucar/nc2/internal/iosp/hdf5/H5header.java#L184

**Comment by JohnLCaron** [comment]
We thought we fixed this at commit https://github.com/Unidata/netcdf-java/commit/0305e989. 

What version of the library are you using?

**Comment by SethChampagneNRL** [comment]
@JohnLCaron I am using 5.1.0, and it looks like the fix you referenced is in the very next version. I will update and see if the issue persists. Thanks!
