### ISSUE TITLE
ConversionException class not found error

### ISSUE THREAD

**Issue by smalyala** [Unidata/netcdf-java#602]
Hi, just upgraded from cdm-4.5.5 to cdm-5.1.0. After doing so, the behavior of `NetcdfDataset.openDataset()` is causing errors for me. What was previously working is now resulting in this error: 
``` 
        2021-02-16T14:35:53.475-05:00	Exception in thread "main" java.lang.NoClassDefFoundError: ucar/units/ConversionException
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.conv.COARDSConvention.checkTimeVarForCalendar(COARDSConvention.java:64)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.conv.CF1Convention.augmentDataset(CF1Convention.java:158)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.enhance(NetcdfDataset.java:469)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.<init>(NetcdfDataset.java:1264)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:442)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:419)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:402)
	2021-02-16T14:35:53.475-05:00	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:388)
```

After looking at the source code, my guess is the **catch** block here is failing: https://github.com/Unidata/netcdf-java/blob/fdf4bdcccdb4b2272c11e97e2482dd41cc1cc94f/cdm/src/main/java/ucar/nc2/units/SimpleUnit.java#L152.

**Comment by lesserwhirls** [comment]
Would you mind trying the same, but with `v5.4.1` (the latest release)?

**Comment by smalyala** [comment]
Hi, thanks for the quick response. I tried with cdm-core-5.4.1.jar but unfortunately same result :(

**Comment by lesserwhirls** [comment]
Would you be able to provide a sample file, or the output from `ncdump -h` (if the file is netCDF)?

**Comment by smalyala** [comment]
Sure thing. This file is rather large around 300 MB. How do you prefer I pass it to you?

**Comment by lesserwhirls** [comment]
If you have a Google account, I believe you could upload a copy of the file on your Google Drive and post a shared link (I'd let you know when I download it so that you could remove access). We also have the ability to accept large files ~[here](https://ramadda.unidata.ucar.edu/repository/entry/upload?group=173e7b2c-b41b-411f-bbc8-40805f467da2)~ (link not working...one moment).

**Comment by lesserwhirls** [comment]
Ok, ignore that last link. If Google Drive isn't an option, the output from `ncdump -h` (or the [java version](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/cdm_utility_programs.html#ncdump), if it's not a netCDF file) might be enough for this particular issue.

**Comment by smalyala** [comment]
Results of `ncdump -h`:

```
netcdf A1X02010000020104001 {
dimensions:
	longitude = 976 ;
	latitude = 301 ;
	number = 51 ;
	time = 1 ;
variables:
	float longitude(longitude) ;
		longitude:units = "degrees_east" ;
		longitude:long_name = "longitude" ;
	float latitude(latitude) ;
		latitude:units = "degrees_north" ;
		latitude:long_name = "latitude" ;
	int number(number) ;
		number:long_name = "ensemble_member" ;
	int time(time) ;
		time:units = "hours since 1900-01-01 00:00:00.0" ;
		time:long_name = "time" ;
		time:calendar = "gregorian" ;
	short tp(time, number, latitude, longitude) ;
		tp:scale_factor = 1.53008751278876e-06 ;
		tp:add_offset = 0.0501348474440366 ;
		tp:_FillValue = -32767s ;
		tp:missing_value = -32767s ;
		tp:units = "m" ;
		tp:long_name = "Total precipitation" ;
	short v10(time, number, latitude, longitude) ;
		v10:scale_factor = 0.000738432207535826 ;
		v10:add_offset = 0.677723740439201 ;
		v10:_FillValue = -32767s ;
		v10:missing_value = -32767s ;
		v10:units = "m s**-1" ;
		v10:long_name = "10 metre V wind component" ;
	short t2m(time, number, latitude, longitude) ;
		t2m:scale_factor = 0.00117529255149839 ;
		t2m:add_offset = 264.454383667201 ;
		t2m:_FillValue = -32767s ;
		t2m:missing_value = -32767s ;
		t2m:units = "K" ;
		t2m:long_name = "2 metre temperature" ;
	short u10(time, number, latitude, longitude) ;
		u10:scale_factor = 0.000795459932132237 ;
		u10:add_offset = 5.07806296339331 ;
		u10:_FillValue = -32767s ;
		u10:missing_value = -32767s ;
		u10:units = "m s**-1" ;
		u10:long_name = "10 metre U wind component" ;
	short d2m(time, number, latitude, longitude) ;
		d2m:scale_factor = 0.00115471427004393 ;
		d2m:add_offset = 259.985788914838 ;
		d2m:_FillValue = -32767s ;
		d2m:missing_value = -32767s ;
		d2m:units = "K" ;
		d2m:long_name = "2 metre dewpoint temperature" ;
	short ssrd(time, number, latitude, longitude) ;
		ssrd:scale_factor = 87.1836784520776 ;
		ssrd:add_offset = 2856660.40816077 ;
		ssrd:_FillValue = -32767s ;
		ssrd:missing_value = -32767s ;
		ssrd:units = "J m**-2" ;
		ssrd:long_name = "Surface solar radiation downwards" ;
		ssrd:standard_name = "surface_downwelling_shortwave_flux_in_air" ;
	short sf(time, number, latitude, longitude) ;
		sf:scale_factor = 1.72833732910119e-07 ;
		sf:add_offset = 0.00566307009253296 ;
		sf:_FillValue = -32767s ;
		sf:missing_value = -32767s ;
		sf:units = "m of water equivalent" ;
		sf:long_name = "Snowfall" ;
		sf:standard_name = "lwe_thickness_of_snowfall_amount" ;
	short msl(time, number, latitude, longitude) ;
		msl:scale_factor = 0.105405864221079 ;
		msl:add_offset = 101333.791047068 ;
		msl:_FillValue = -32767s ;
		msl:missing_value = -32767s ;
		msl:units = "Pa" ;
		msl:long_name = "Mean sea level pressure" ;
		msl:standard_name = "air_pressure_at_mean_sea_level" ;
	short ptype(time, number, latitude, longitude) ;
		ptype:scale_factor = 0.000122075900691255 ;
		ptype:add_offset = 3.99993896204965 ;
		ptype:_FillValue = -32767s ;
		ptype:missing_value = -32767s ;
		ptype:units = "code table (4.201)" ;
		ptype:long_name = "Precipitation type" ;
	short fzra(time, number, latitude, longitude) ;
		fzra:scale_factor = 1.19858698495429e-07 ;
		fzra:add_offset = 0.00392729011490124 ;
		fzra:_FillValue = -32767s ;
		fzra:missing_value = -32767s ;
		fzra:units = "m" ;
		fzra:long_name = "Accumulated freezing rain" ;
	short fg10(time, number, latitude, longitude) ;
		fg10:scale_factor = 0.00068258359038464 ;
		fg10:add_offset = 22.6350177868505 ;
		fg10:_FillValue = -32767s ;
		fg10:missing_value = -32767s ;
		fg10:units = "m s**-1" ;
		fg10:long_name = "10 metre wind gust since previous post-processing" ;

// global attributes:
		:Conventions = "CF-1.6" ;
		:history = "2021-02-01 07:01:51 GMT by grib_to_netcdf-2.12.0: /home/ec2-user/eccodes/bin/grib_to_netcdf -o tmp/year=2021/month=02/day=01/hour=00/A1X02010000020104001.nc tmp/year=2021/month=02/day=01/hour=00/A1X020100000201040012" ;
}
```

**Comment by smalyala** [comment]
Hi, following up on this. Sorry for the rush but this issue is pressing for us because it's blocking deployments.

**Comment by JohnLCaron** [comment]
The NoClassDefFoundError implies that the udunits.jar is not on the classpath. 

What does your classpath look like, ie what does the java command line look like that generates the error?

**Comment by smalyala** [comment]
I have all the code and dependencies in a JAR file and run it in a docker container. This is the command I use as the entrypoint: `ENTRYPOINT ["java", "-Xmx15g", "-Xms15g", "-jar","PackageName-1.0.jar"]`

**Comment by JohnLCaron** [comment]
Its likely that for some reason your jar does not contain the package ucar.units.

**Comment by smalyala** [comment]
I see. I downloaded this jar to use as my dependency: https://artifacts.unidata.ucar.edu/#browse/browse:unidata-all:edu%2Fucar%2Fcdm%2F5.1.0%2Fcdm-5.1.0.jar. Is the `ucar.units` package not included in this jar? If it is, do you know what I need to do to make it findable?

**Comment by JohnLCaron** [comment]
Use https://artifacts.unidata.ucar.edu/#browse/browse:unidata-releases:edu%2Fucar%2FnetcdfAll%2F5.4.1%2FnetcdfAll-5.4.1.jar

**Comment by smalyala** [comment]
The `open_dataset()` function seems to be working okay now but later on I'm getting a different error. Could you please send me the documentation link for this specific package? I'm wondering if `NetcdfDataset.getVariables()` or `NetcdfDataset.findVariable(var)` have changed because the new error I'm getting is related to these two functions.

**Comment by smalyala** [comment]
Following up on this

**Comment by lesserwhirls** [comment]
There have been some changes between `4.5.5` to `5.1.0` for sure (but you definitely want to use `5.4.1`). If the issue you are running into now is related to the move from `4.5.5` to `5.1.0`, then this section of the documentation might be helpful:

https://docs.unidata.ucar.edu/netcdf-java/current/userguide/upgrade_to_50.html

In terms of those two methods, the javadocs for the current version might be helpful:

https://docs.unidata.ucar.edu/netcdf-java/current/javadoc/ucar/nc2/dataset/NetcdfDataset.html

**Comment by smalyala** [comment]
Thanks for the link. Seems like the return type of `getVariables()` changes from a regular List<Variable> to an ImmutableList<Variable> from `4.5.5` to `5.4.1` which broke our code as we were modifying the returned list. It would be helpful if that was noted in the changes section. Also, I'm curious of the reasoning to change to ImmutableList :)

Thanks again for the help!

**Comment by lesserwhirls** [comment]
For sure - that change was made in 5.4.1. The [upgrade section for 5.4.x](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/upgrade_to_50.html#netcdf-java-api-changes-54x) says that many of the changes in that release were related to [establishing a public API](https://www.unidata.ucar.edu/blogs/developer/entry/netcdf-java-looking-ahead), and that those changes were described on the [project github wiki](https://github.com/Unidata/netcdf-java/wiki#public-api-details) (more details can be found there). The section explicitly talking about Immutable returns can be found [here](https://github.com/Unidata/netcdf-java/wiki/Common-Client-Changes#changing-collection-return-types-to-immutable).
