### ISSUE TITLE
C.S. returns wrong projection handler

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#605]
Working with a 5.4.2 SNAPSHOT from this past week.

A user sent me a couple datasets, both HDF5/NC4. Both are lon-lat data with metadata specifying that they are gridded using the `transverse_mercator` projection. Although the metadata are close to identical, when Panoply opens the datasets in enhanced mode and then tries to plot a `Variable` within, the result varies. With one dataset, querying one variable for its coordinate system and then CS for the projection handler, the result is the expected `TransverseMercatorProjection` class and plotting is just fine. However, with the second, the CS returns the very much unexpected `LatLonProjection` class and... ugh.

From the case that is going awry, the metadata looks like

```
float air_temperature_2m(time=1, y=128, x=114);
  :grid_mapping = "transverse_mercator";
int transverse_mercator;
  :grid_mapping_name = "transverse_mercator";
  :longitude_of_central_meridian = 9.0; // double
  :false_easting = 500000.0; // double
  :false_northing = 0.0; // double
  :latitude_of_projection_origin = 0.0; // double
  :scale_factor_at_central_meridian = 0.9996; // double
  :semi_major_axis = 6378137.0; // double
  :inverse_flattening = 298.257223563; // double
  :spatial_ref = "PROJCS[\"UTM Zone 32, Northern Hemisphere\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",9],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"Meter\",1],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]";
  :utm_zone_number = 32; // int
  :proj4 = "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs";
```

(FWIW, the data area is in central Norway.)

At the moment I have a workaround in place such that if the returned projection class is not what is expected from the `grid_mapping` attribute, then to instead use the 2D auxiliary lon and lat coordinate variables. But that only works if those variables are present.

Thus, any insight on how NJ might be returning the wrong projection class?

**Comment by JohnLCaron** [comment]
Hi @rschmunk can you send a link to sample data? What version of the library do you see this on? Thanks.

**Comment by rschmunk** [comment]
@JohnLCaron, See [file 1](https://www.dropbox.com/s/gfm38it2lf0pc7k/seNorge_v2_0_TEMP1h_grid_2021021813.nc?dl=1) and [file 2](https://www.dropbox.com/s/seq9fa81u2auuze/DSSF_hourly_Region.nc?dl=1). (First file 300 kB, second 2.5 MB)

Both are TM gridded but when I try to make a plot of the `air_temperature_2m` variable in file 1, querying the coordinate system for that var via the following returns the `LatLonProjection`.  There is no problem getting the correct projection when plotting the `GlobRad` variable in file 2.

```
        final VariableDS njvarDS = (VariableDS)ncvar_.getObject ( );
        final List<CoordinateSystem> csList = njvarDS.getCoordinateSystems ( );
        final CoordinateSystem cs = csList.get (0);
        final Projection pj = cs.getProjection ( );
```

**Comment by JohnLCaron** [comment]
The difference is that the second file has  global attribute

`  :Conventions = "CF-1.6";`

But the first one doesnt, so the "grid_mappping" doesnt get picked up.

**Comment by rschmunk** [comment]
@JohnLCaron, I missed that. But somehow this strikes me as... cough... a deficiency in the `DefaultConventions` class. Or am I being too picky?

**Comment by JohnLCaron** [comment]
Yeah, it would be reasonable to review DefaultConventions and consider if it should use more of CF.

But it is for sure a defect in the file itself.

**Comment by rschmunk** [comment]
@JohnLCaron, So it seems that `DefaultConventions` currently isn't able to handle projected grids, as it apparently pays no attention to the `grid_mapping_name` attribute?

**Comment by JohnLCaron** [comment]
Correct. DefaultConventions is a "if someone doesnt know enough to use
conventions, whats the best we can do?"

grid_mapping_name is a CF thing, it relies on CF vocabularies etc. So, add
CF convention attribute.

For one-offs, you can wrap in NcML if you want.

**Comment by JohnLCaron** [comment]
See Issue #637.
