### ISSUE TITLE
ucar.nc2.NetcdfFile.toString() method doesn't produce CDL that can be processed

### ISSUE THREAD

**Issue by robert-lil** [Unidata/netcdf-java#615]
Version:
```
<groupId>edu.ucar</groupId>
<artifactId>netcdf4</artifactId>
<version>5.4.1</version>
```

Hi, when I generate a cdl file with ucar.nc2.NetcdfFile.toString() method I don't get a valid CDL file. I am creating it with the following code:
```Java
try (NetcdfFile ncfile = NetcdfFiles.open(file.toString())){
    String cdl = ncfile.toString();
    FileWriter fw = new FileWriter("src/main/resources/output/" + cdlFileName);
    fw.write(cdl);
    fw.close();
}
```
I then try to generate a netCDF file with ```ncgen``` version 4.7.4 (I do have a use case for doing this!) with the following and get the error:
```Bash
user:~/environment $ ncgen -b file.cdl 
ncgen: file.cdl line 7: syntax error, unexpected '=', expecting ',' or ')'
```

It doesn't create the "empty" netcdf file with just the header. It looks like the method isn't producing valid CDL. I have tried this with several files from different datasets and get the same issue.

Many thanks,
Rob

**Comment by lesserwhirls** [comment]
The `toString()` method does not produce a strict CDL representation. If you want strict CDL, try something like the following:

~~~java
try (NetcdfFile ncfile = NetcdfFiles.open(file.toString())){
  Formatter f = new Formatter();
  ncf.writeCDL(f, new Indent(2), true);
  String cdl = f.toString();
}
~~~

Does that result in output that can be used by `ncgen`?

**Comment by robert-lil** [comment]
Thanks @lesserwhirls I have been able to generate a correct CDL file!
