### ISSUE TITLE
What is the replacement of CoordSysBuilder?

### ISSUE THREAD

**Issue by desruisseaux** [Unidata/netcdf-java#616]
Hello

`ucar.nc2.dataset.CoordSysBuilder` is deprecated in UCAR netCDF library 5.4.1, but I didn't see a replacement in the [Upgrading to netCDF-Java version 5.x](https://docs.unidata.ucar.edu/netcdf-java/5.2/userguide/upgrade_to_50.html#netcdf-java-api-changes-52x) page. What would be the new way to build a `CoordinateSystem` from a `NetcdfDataset` using custom conventions? For example:

```java
class BuilderForMyNonStandardFile extends CoordSysBuilder {
    /**
     * Use some format-specific convention for identifying which variables are axes.
     */
    @Override
    protected void findCoordinateAxes(NetcdfDataset ds) {
        for (VarProcess vp : varList) {
            vp.isCoordinateVariable = // Some custom criterion here.
        }
    }

    /**
     * Identifies what kind of axis the given variable is
     * using a convention specific to a particular file.
     */
    @Override
    protected AxisType getAxisType(NetcdfDataset ds, VariableEnhanced variable) {
        String name = variable.getShortName();
        if (CharSequences.startsWith(name, "Longitude", true)) return AxisType.Lon;
        if (CharSequences.startsWith(name, "Latitude",  true)) return AxisType.Lat;
        return super.getAxisType(ds, variable);
    }
}
```

Above builder is used as below:

```java
NetcdfDataset ds = ...;
val builder = new BuilderForMyNonStandardFile();
builder.buildCoordinateSystems(ds);
List<CoordinateSystem> systems = ds.getCoordinateSystems();
```

How to do something equivalent in latest versions of the library?

Thanks!

**Comment by lesserwhirls** [comment]
Greetings @desruisseaux!

The docs for the latest version can be found at:

https://docs.unidata.ucar.edu/netcdf-java/current/userguide/upgrade_to_50.html#netcdf-java-api-changes-54x

but that entry would direct you to the wiki page for common client changes, but more specifically this is what you are looking for:

https://github.com/Unidata/netcdf-java/wiki/Common-Client-Changes#service-provider-interfaces

The new way is to use the Service Provider Interface and have the builder implement [ucar.nc2.dataset.spi.CoordsystemBuilderFactory](https://github.com/Unidata/netcdf-java/wiki/Common-Client-Changes#ucarnc2datasetspicoordsystembuilderfactory) ([javadoc](https://docs.unidata.ucar.edu/netcdf-java/current/javadoc/ucar/nc2/dataset/spi/CoordSystemBuilderFactory.html)). However, implementing that will require you to use `ucar.nc2.internal.dataset.CoordSystemBuilder` as a return from `open`, and that does not quite feel right.

@JohnLCaron - it does not look like this changed in 6 (would still need to rely on an internal class) - what do you think would be the best way to bubble that up?

**Comment by JohnLCaron** [comment]
Yes, you have to use ucar.nc2.internal.dataset.* to write a custom
CoordSystemBuilder. So expect that for each major version, there may be
some breakage requiring tweakage. But not for minor upgrades.

This prioritizes a smaller API surface vs a previous hope that there would
be lots of contributors.

**Comment by desruisseaux** [comment]
Thanks Sean and John. This `ucar.nc2.internal.dataset.CoordSystemBuilder` class seems similar in spirit to the old `ucar.nc2.dataset.CoordSysBuilder` class. I will try it tomorrow.

It should not be a problem for me if that class changes in a future release because my `CoordSysBuilder` subclass is small. Changes should be manageable. However if version 6 or 7 starts using Jigsaw modules and if `ucar.nc2.internal.*` packages are not exported, then I would have some difficulties if that class or an equivalent functionality is not accessible in a public package…

For information I use it for loading [GCOM images from JAXA](https://gportal.jaxa.jp/gpr/), which use conventions different than CF-Conventions.

**Comment by JohnLCaron** [comment]
Thanks, Martin. Thats a really good point about Jigsaw modules. We will
factor that in when we start to tackle Jigsaw.

**Comment by desruisseaux** [comment]
Done and it seems to work. For information regarding what may be in a public API, I override the following `ucar.nc2.internal.dataset.CoordSystemBuilder` methods:

* `protected void identifyCoordinateAxes()`
* `protected AxisType getAxisType(VariableDS.Builder)`

I let you decide if this issue should be kept open as a reminder for public API or be closed.

**Comment by lesserwhirls** [comment]
Thank you for that helpful feedback about what you use from the `CoordSystemBuilder class`, and for the reminder to keep in mind how JPMS will impact things going forward. I would like to start playing with writing `module-info.java` files for our gradle subprojects in version 6.
