### ISSUE TITLE
Wrong guava version

### ISSUE THREAD

**Issue by ofrisberg** [Unidata/netcdf-java#625]
When I try to use WmoCodeFlagTables.readGribCodes I get the following error:

com.google.common.collect.ImmutableList.toImmutableList()
java.lang.NoSuchMethodError

toImmutableList was added in guava version 21. I use the jar version 5.4.1 downloaded from https://www.unidata.ucar.edu/downloads/netcdf-java/.

Thanks in advance!

**Comment by lesserwhirls** [comment]
Thank you for the report! NetCDF-Java 5.4.1 uses Guava 28.0, and `netcdfAll-5.4.1.jar` contains `com/google/common/collect/ImmutableList.toImmutableList.class`. Is it possible an older version of Guava is being found on your classpath before the netcdfAll jar?

**Comment by ofrisberg** [comment]
Yes, the problem was on my side!
