### ISSUE TITLE
Failing tests in Jenkins

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#677]
Any tests still failing in Jenkins.

**Comment by JohnLCaron** [comment]
Most of the tests seem to be ones requiring ncx4 files to have been generated.
Now sure what we were doing before where this didnt happen?

**Comment by JohnLCaron** [comment]
Most BUFR files in "formats/bufr/userExamples" are failing for TestGcdmNetcdfFile. Looks like char vars only? Looks like it broke when CHAR recoded as BYTE. Will submit PR.

**Comment by JohnLCaron** [comment]
thredds.inventory.s3.TestMFileS3.bucketAndKeyOsdc

Stacktrace
expected: 1611593614000
but was : 1619161328000
	at thredds.inventory.s3.TestMFileS3.checkWithBucketAndKey(TestMFileS3.java:200)
	at thredds.inventory.s3.TestMFileS3.bucketAndKeyOsdc(TestMFileS3.java:112)

thredds.filesystem.s3.TestControllerS3.testGetInventoryTopBucketDelimiterAws

Stacktrace
expected: 1
but was : 3
	at thredds.filesystem.s3.TestControllerS3.checkInventoryTopCount(TestControllerS3.java:294)
	at thredds.filesystem.s3.TestControllerS3.testGetInventoryTopBucketDelimiterAws(TestControllerS3.java:90)

**Comment by lesserwhirls** [comment]
> Most of the tests seem to be ones requiring ncx4 files to have been generated.
> Now sure what we were doing before where this didnt happen?

The `.ncx4` files do not exists at the time the gCDM tests run. If I run the `:cdm-test:testIndexCreation` task first before anything else, then the `ncx4` files are available for the gCDM tests. My guess is that by renaming the gradle project, it changed the order of the tests and `cdm-test` no longer ran first. I have things running in order on Jenkins, and we're down to five failing tests (three once Unidata/netcdf-java#683 goes in).
