### ISSUE TITLE
Gradle 7

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/netcdf-java#684]
Rather than migrating the current build (which is itself a vestige of Gradle 3) to Gradle 7, rearchitect the build from scratch using the current best practices. This will allow us the opportunity to shed complexity and ease upgrades to major versions in the future. It might be possible to backport these changes to earlier versions of netCDF-Java, but for now we won't worry about that.

Once the `develop` branch is bumped to `7.0.0-SNAPSHOT`, I'll remove the current Gradle infrastructure and begin working on getting the `udunits`, `httpservices`, and `cdm-core` Gradle projects building, and their tests running, which would be the minimum viable product for the library.

**Comment by JohnLCaron** [comment]
Also see #655.
