### ISSUE TITLE
Jenkins failing

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#695]
Caused by: java.lang.IllegalArgumentException: Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

**Comment by JohnLCaron** [comment]
https://jenkins-aws.unidata.ucar.edu/job/netcdf-java_develop/259/consoleText

**Comment by lesserwhirls** [comment]
Yeah, I hadn't run the tests since I updated the jenkins build config to use java 11. It's running now though. I did run the tests on your branch though:

https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/20/

Looks like there were 8 failures on that one.
