### ISSUE TITLE
Evaluate opendap client code for long term maintainence and risks

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#697]
This code is so old, Im not sure we should keep it.
Its possible we need to withdraw it until we can evaluate and rewrite it if needed.

**Comment by JohnLCaron** [comment]
Im delaying the removeal of cdm-lite since thats the local testing framework for the opendap server.

**Comment by JohnLCaron** [comment]
Im torn about keeping the opendap module. Its a huge amount of work to bring up to speed, and I wonder if its worth it.

**Comment by JohnLCaron** [comment]
Id like to discuss the possibility of abandoning opendap in ver8

**Comment by dopplershift** [comment]
Doesn't this imply that netcdf-java would no longer be able to communicate with all DAP servers?

**Comment by lesserwhirls** [comment]
Yes, that's correct. If it becomes a need, the client can be rewritten from scratch, possibly in a separate Java-based project. Currently, though, it's simply unmaintainable. From what I understand, Unidata plans on supporting netCDF-Java version 5.x long-term, and we're talking about removing this code in version 8.
