### ISSUE TITLE
NCZarr support

### ISSUE THREAD

**Issue by thomafred** [Unidata/netcdf-java#723]
NCZarr was released with netcdf 4.8, yet I cannot find any reference to it in this repo.

Will this be implemented with version 6, and if so - how do I use it?

**Comment by haileyajohnson** [comment]
Thanks for the question! We are actively developing support for reading both strict zarr (v2) and NCZarr formats using the netCDF-Java library. Once completed, zarr/NCZarr reads will be supported in versions 5 and up. 

You'll be able to read zarr data the same way you would read other data formats through the cdm-core public API (i.e. using `NetcdfFiles`).
