### ISSUE TITLE
Include LICENSE infor in published artifacts

### ISSUE THREAD

**Issue by laeubi** [Unidata/netcdf-java#754]
Currently the jar files do not include the LICENSE file, it would be good to include this alongside the jar so automatic tools can analyses/display the license automatically.

**Comment by lesserwhirls** [comment]
This is very much doable. Thank you for pointing out that the LICENSE file was missing! It seems like `META-INF/LICENSE` is a pretty common spot - does that work for your purposes?

**Comment by laeubi** [comment]
yep, that would be suitable!
