### ISSUE TITLE
[5.x] (and later?): Unable to open dataset due to exception in H5headerNew

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#797]
### Versions impacted by the bug

v5.x

### What went wrong?

A user is trying to open a dataset in Panoply, which is using a 5.4.2-SNAPSHOT from a month or two ago. Although it has an `NC` filename extension, the file is apparently some from of HDF5. So when code in Panoply calls `NetcdfDatasets.acquireDataset`, the acquire fails due an exception thrown by `H5headerNew`.

Unfortunately, all that percolates up from NJ and is caught in my code is an
`IOException opening dataset: java.io.IOException: java.io.IOException: java.lang.IllegalStateException: Cant find Heap Object,heapId= nelems=0 heapAddress=0 index=0`

After adding some extra error logging to NJ, I at least extracted that
`000012 SEVERE: H5headerNew readHeapString - Cant find Heap Object, heapIdAddress=128614, heapId= nelems=0 heapAddress=0 index=0`

A copy of the offending dataset can be downloaded [from here on Dropbox](https://www.dropbox.com/s/lwtxfp9kua67ws1/GOLD_L1C_CHA_DAY_2021_206_21_52_v03_r01_c01.nc?dl=0). It originates from a [UCF data repository](https://gold.cs.ucf.edu/data/search/).

Is this a bug in NJ? Something weird in the dataset? Something else?

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by lesserwhirls** [comment]
NetCDF-4 files are HDF5 files that, essentially, follow a metadata spec. The NetCDF Users Guide says "the netCDF-4 format intentionally uses a limited subset of the HDF5 data model and file format features.", but it does not explicitly list what those are...and so now that has become a moving target. It looks like the root issue here is that around version `4.3.1`, netCDF-C started to allow for a `NULL` string, in addition to a zero length strings, to provide better interoperability with HDF5 (the [netcdf-4 spec](https://www.unidata.ucar.edu/software/netcdf/documentation/4.7.4-pre/file_format_specifications.html#netcdf_4_spec) says nothing of this). The netCDF-Java library is barfing on the use of a `NULL` string value for the attribute `VAR_NOTES` on the variable `GRID_EW`. When using `ncdump`, the value of the attribute is the string `NIL`, which represents the `NULL` string case (as opposed to `''` for the empty string case).

I suppose the thing to do would be to set the value of the attribute to the string `NIL` in these cases.

**Comment by rschmunk** [comment]
Thanks for the quick work, @lesserwhirls. This should at least make one Argentine user of Panoply very happy. 😀

**Comment by rschmunk** [comment]
Great, the update allowed me to open the problem datasets without problem. Then I found out the creators used some offbeat convention such that NJ doesn't discover a coordinate system. 🙄
