### ISSUE TITLE
Grib2 data template 50002 bug in data decoding.

### ISSUE THREAD

**Issue by iapafoto** [Unidata/netcdf-java#881]
### Versions impacted by the bug

v5.x

### What went wrong?

Problem with decimal_scale_factor in Grib2DataReader2.java  getData50002()

ret[i] = (((data[i] * EE) + R) * DD);
must be
ret[i] = (((data[i] * EE) + R) / DD);

or 

float DD = (float) java.lang.Math.pow((double) 10, (double) D);
must be
float DD = (float) java.lang.Math.pow((double) 10, (double) -D);

rq: in c source
https://github.com/erdc/grib_api/blob/master/src/grib_accessor_class_data_g1second_order_general_extended_packing.c

d = grib_power(-decimal_scale_factor,10) ;
values[i] = (double) (((X[i]*s)+reference_value)*d);

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

No

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by JohnLCaron** [comment]
Hi Sebastion, thanks for the fix!. Do you happen to have a GRIB file using
dataTemplate 50002 that we can test against? -John

**Comment by JohnLCaron** [comment]
Im adding this fix to ver8.
Need to add to ver5.

**Comment by iapafoto** [comment]
Hi John,
Please find attached a grib in 50002 format. The decimal_scale_factor is applied in the wrong way with the current version. The decoded values ​​should be around 300 Kelvin (floor temperature)

[](url
[MeteoFrance_Indonesia_T__ISOBARIC_1000_HPA_50002.zip](https://github.com/Unidata/netcdf-java/files/7344007/MeteoFrance_Indonesia_T__ISOBARIC_1000_HPA_50002.zip)
)

**Comment by JohnLCaron** [comment]
@iapafoto : Thanks, looks great

**Comment by haileyajohnson** [comment]
addressed by #892, #897, #898, and #899
