### ISSUE TITLE
Produce stable 8.0.0 version

### ISSUE THREAD

**Issue by mgwidmann** [Unidata/netcdf-java#953]
I have the following in my `pom.xml` to use the `8.0.0-SNAPSHOT` from artifacts.unidata.ucar.edu

```
    <properties>
        <netcdfJavaVersion>8.0.0-SNAPSHOT</netcdfJavaVersion>
    </properties

    <repositories>
        <repository>
            <id>unidata-all</id>
            <name>Unidata All</name>
            <url>https://artifacts.unidata.ucar.edu/repository/unidata-all/</url>
        </repository>
   </repositories>

   <dependencies>
      <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>cdm-core</artifactId>
            <version>${netcdfJavaVersion}</version>
            <scope>compile</scope>
        </dependency>
   </dependencies>
```

The project is setup with continuous integration and publishing to the nexus repository. When backwards incompatible changes are merged, it causes my builds to break when no code changes occurred on my end. For example, recently I've had to fix things like `file.getVariables()` to `file.getAllVariables()`, as well as `file.getGlobalAttributes()` to `file.getRootGroup().attributes()`.

The latest published stable version is listed in the nexus repo as `5.4.2` or `6.0.0-beta1`, but these dependencies are far too old for me to use. Please publish a `8.0.0` which is stable and not updated and then publish new versions (8.0.1 or 8.1.0, etc) for patches and updates and keep backwards incompatible changes to major (`8.x.x` -> `9.x.x`) version changes. It would be best to use [semantic versioning](https://semver.org/).

**Comment by dopplershift** [comment]
5.4.2 is the current latest stable release, made in August 2021, so I'm not sure how
> these dependencies are far too old for me to use

The 8.x branch has not had a release, is undergoing a major refactor with the intention of breaking APIs, and is not considered ready for production use. I'll defer to @haileyajohnson and @JohnLCaron on when that's ready for release, but my feeling is not "soon".

If you want stability, follow the semantic versioning we've been using and please stick with the 5.x branch.
