### ISSUE TITLE
Add more robust handling of time units/datetimes

### ISSUE THREAD

**Issue by haileyajohnson** [Unidata/netcdf-java#979]
From support ticket:

When time unit contains an extra space, e.g.
```
double time(time) ;
time:units = "days since 1800-1-1 00:00:0.0" ;
```
netCDF-Java throws: `java.lang.IllegalStateException: CoordinateSystem does not have a usable time axis`

CF convention doesn't explicitly say that there only has to be one space, only that it has to be compatible with
udunits, and udunits is capable of reading time with the extra space, so it would be nice for netCDF-Java to support it as well.

**Comment by mnlerman** [comment]
I wasn't able to reproduce the exception using the example provided. Based on the context from the original user support request, I added an extra space between the date and the time and was able to reproduce the exception 
```
double time(time) ;
time:units = "days since 1800-1-1  00:00:0.0" ;
```
`java.lang.IllegalStateException: CoordinateSystem does not have a usable
time axis`
