### ISSUE TITLE
Source code for version 4.6.14

### ISSUE THREAD

**Issue by ggdupont** [Unidata/netcdf-java#98]
* version with which you are encountering an issue: 4.6.14
* environmental information: N/A
* a description: 
I'm using netcdf-java in a project but I encountered issues with overwritted google-guava dependencies. It seems to be hidden in netcdf but not at the same version of my project. 
Thus, I'm looking for the codebase of the 4.6.14 to double check the dependencies and versions. Where is it? Moreover, could you explain a bit on the build process so I could devise how to overcome the library collision I face.

Note: the release note (here: https://www.unidata.ucar.edu/blogs/news/entry/netcdf-java-library-and-tds9) point to this repo, but there is no tag for 4.6.14

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by lesserwhirls** [comment]
Greetings!

Version 4.6.14 of the netCDF-Java library (as well as the THREDDS Data Server) lives here:

https://github.com/Unidata/thredds/

and the tag for that version specifically is here:

https://github.com/Unidata/thredds/releases/tag/v4.6.14

Our dependencies and their versions are managed in [gradle/dependencies.gradle](https://github.com/Unidata/thredds/blob/master/gradle/dependencies.gradle). For `guava` specifically, looks like we're using `com.google.guava:guava:27.0.1-jre`. We use gradle to build, so once you have cloned the repository, you can simply run:

`./gradlew clean assemble`

and the various jar files will be assembled. More information can be found [here](https://www.unidata.ucar.edu/software/netcdf-java/v4.6/tutorial/SourceCodeBuild.html).

Cheers!
